'use client';
import { useState } from 'react';
import { Card } from '@/components/shared';
import { buttonClass, inputClass } from '@/components/projects/fields';
import { addWatchAssets, assetKey, previewWatchImport, watchProviderNames, type WatchAsset } from '@/lib/watchlists';
import { useWatchlists } from './store';
export function WatchImport({ listId, catalog, loading }: { listId: string; catalog: WatchAsset[]; loading: boolean }) {
  const store = useWatchlists(); const [raw, setRaw] = useState(''); const [preview, setPreview] = useState<ReturnType<typeof previewWatchImport> | null>(null); const [choices, setChoices] = useState<Record<string,string>>({}); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  function prepare(e: React.FormEvent) { e.preventDefault(); setError(''); setNotice(''); try { const rows = previewWatchImport(raw,catalog); setPreview(rows); setChoices(Object.fromEntries(rows.map(r => [r.token,r.matches.length === 1 ? assetKey(r.matches[0]) : r.matches.length === 0 ? 'skip' : '']))); } catch(e) { setPreview(null); setError(e instanceof Error ? e.message : 'Invalid pasted list.'); } }
  const unresolved = preview?.some(r => !choices[r.token]);
  const assets = (preview ?? []).flatMap(r => { const a = r.matches.find(a => assetKey(a) === choices[r.token]); return a ? [a] : []; });
  function confirm() {
    if (unresolved || !assets.length) return; const now = new Date().toISOString(); const unique = new Set(assets.map(assetKey)).size;
    const ok = store.commit(f => {
      if (!f.lists.some(l => l.id === listId && !l.archived)) throw Error('Select an active watchlist.');
      return { ...f, lists: f.lists.map(l => l.id === listId ? addWatchAssets(l,assets,now) : l) };
    });
    if (ok) { setNotice(`${unique} exact asset${unique === 1 ? '' : 's'} confirmed. Existing entries, notes and statuses were kept; skipped rows were not added.`); setPreview(null); setRaw(''); }
  }
  return <Card className="space-y-3 p-4"><h2 className="text-sm font-semibold">Paste a token list</h2><p className="text-xs text-muted-foreground">Names, tickers or exact IDs such as cmc:1, coinpaprika:btc-bitcoin or coingecko:bitcoin. Separate with commas or new lines. Review the source and asset before adding.</p><form onSubmit={prepare} className="space-y-3"><textarea aria-label="Paste watchlist tokens" className={inputClass} rows={4} value={raw} maxLength={20000} placeholder={'BTC\nETH\nQNT'} onChange={e => { setRaw(e.target.value); setPreview(null); setNotice(''); }} /><button className={buttonClass} disabled={!store.ready || loading || !raw.trim()}>Preview matches</button></form><p className="text-[10px] text-muted-foreground">Matches use connected CMC top 100, CoinPaprika market and CoinGecko trending snapshots. Missing tokens can be added later from Discovery. This is a pasted list, not CMC account sync or portfolio import.</p>{(error || notice) && <p role="status" className="text-xs text-warning">{error || notice}</p>}{preview && <><div className="space-y-3">{preview.map(r => <div className="rounded-xl border border-border/50 p-3" key={r.token}><p className="mb-2 break-words text-xs font-medium">{r.token}<span className="ml-2 text-[10px] text-muted-foreground">{r.matches.length > 1 ? 'Multiple matches · choose explicitly' : !r.matches.length ? 'Not found in these snapshots' : 'One match · review identity'}</span></p><select aria-label={`Match ${r.token}`} value={choices[r.token] ?? ''} className={inputClass} onChange={e => setChoices(v => ({ ...v,[r.token]:e.target.value }))}>{r.matches.length > 1 && <option value="">Choose an asset or skip</option>}<option value="skip">Skip this row</option>{r.matches.map(a => <option key={assetKey(a)} value={assetKey(a)}>{a.name} ({a.symbol}) · {watchProviderNames[a.provider]} · {a.id}</option>)}</select></div>)}</div><p className="text-xs text-muted-foreground">{new Set(assets.map(assetKey)).size} assets selected · {preview.filter(r => choices[r.token] === 'skip').length} skipped{unresolved && ' · resolve the remaining matches'}</p><button className={buttonClass} disabled={!store.ready || unresolved || !assets.length} onClick={confirm}>Confirm selected assets</button><button className={`${buttonClass} ml-2`} onClick={() => setPreview(null)}>Cancel preview</button></>}{store.error && <p role="alert" className="text-xs text-warning">{store.error}</p>}</Card>;
}
