'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Card } from '@/components/shared';
import { buttonClass, inputClass } from '@/components/projects/fields';
import { marketColumns, defaultMarketColumns, validMarketColumns } from '@/lib/market-columns';
import { filterMarketRows, invalidRange, type MarketRange, type MarketSort } from '@/lib/market-dashboard';
import { assetKey, watchHref, watchProviderNames, watchStatuses, watchRows, type Watchlist } from '@/lib/watchlists';
import type { MarketQuote } from '@/services/core/types';
import type { DiscoverySnapshot } from '@/lib/discovery';
import { Change, FeedNote, money, price } from '@/components/dashboard/panels';
import type { Feed } from '@/components/dashboard/use-feed';
import { useWatchlists } from './store';
export function WatchTable({ list, cmc, paprika, gecko, compact = false }: { list: Watchlist; cmc: Feed<MarketQuote[]>; paprika: Feed<MarketQuote[]>; gecko: Feed<DiscoverySnapshot>; compact?: boolean }) {
  const store = useWatchlists(); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [archived, setArchived] = useState(false); const [shown, setShown] = useState(30);
  const [sort, setSort] = useState<MarketSort | null>(null); const [descending, setDescending] = useState(false); const [ranges, setRanges] = useState<MarketRange[]>([]); const [filters, setFilters] = useState(false); const [picker, setPicker] = useState(false); const [columns, setColumns] = useState(defaultMarketColumns); const [columnsReady, setColumnsReady] = useState(false);
  const [editing, setEditing] = useState(''); const [base, setBase] = useState(''); const [notes, setNotes] = useState(''); const [editStatus, setEditStatus] = useState<typeof watchStatuses[number]>('Watching'); const [notice, setNotice] = useState('');
  useEffect(() => { try { const raw = localStorage.getItem('atlas.watchlist.columns.v1'); const parsed = raw && validMarketColumns(JSON.parse(raw)); if (parsed) setColumns(parsed); } catch { /* Invalid UI preferences cannot affect records. */ } setColumnsReady(true); }, []);
  useEffect(() => { if (columnsReady) { try { localStorage.setItem('atlas.watchlist.columns.v1', JSON.stringify(columns)); } catch { /* Table still works without preference storage. */ } } }, [columns, columnsReady]);
  const metrics = watchRows(list.entries, cmc.data ?? [], paprika.data ?? [], gecko.data, archived);
  const found = metrics.filter(r => (status === 'all' || r.entry.status === status) && (!query.trim() || `${r.name} ${r.symbol} ${r.entry.asset.id}`.toLowerCase().includes(query.trim().toLowerCase())));
  const filtered = filterMarketRows(found, 0, 0, sort, descending, ranges); const visible = filtered.slice(0, compact ? 5 : shown);
  const selectedColumns = compact ? marketColumns.filter(c => ['price','change24hPercent'].includes(c.key)) : columns.map(key => marketColumns.find(c => c.key === key)!);
  function chooseSort(key: MarketSort) { if (sort === key) setDescending(v => !v); else { setSort(key); setDescending(key !== 'name' && key !== 'rank'); } }
  function save(e: React.FormEvent) {
    e.preventDefault(); const now = new Date().toISOString(); const ok = store.commit(f => ({ ...f, lists: f.lists.map(l => {
      if (l.id !== list.id) return l; const existing = l.entries.find(e => assetKey(e.asset) === editing);
      if (!existing || existing.updatedAt !== base) throw Error('This entry changed. Copy your note, then reload and reopen it before saving.');
      return { ...l, updatedAt: now, entries: l.entries.map(e => assetKey(e.asset) === editing ? { ...e, notes, status: editStatus, updatedAt: now } : e) };
    }) })); if (ok) { setEditing(''); setNotice('Note and status saved.'); }
  }
  function archive(key: string, next: boolean) { const now = new Date().toISOString(); const ok = store.commit(f => ({ ...f, lists: f.lists.map(l => l.id === list.id ? { ...l, updatedAt: now, entries: l.entries.map(e => assetKey(e.asset) === key ? { ...e, archived: next, updatedAt: now } : e) } : l) })); if (ok) { setEditing(''); setNotice(next ? 'Asset archived. Use Archived assets to restore it.' : 'Asset restored.'); } }
  return <Card className="min-w-0 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-2 p-4"><h2 className="text-sm font-semibold">{list.name}</h2><span className="text-[10px] text-muted-foreground">{list.entries.filter(e => !e.archived).length} assets{compact && <Link href="/watchlists" className="ml-3 text-primary">Manage →</Link>}</span></div>
    {!compact && <div className="space-y-3 px-4 pb-4"><div className="flex flex-wrap gap-2"><input aria-label="Search watchlist" placeholder="Search assets" className={`${inputClass} min-w-0 flex-1`} value={query} onChange={e => { setQuery(e.target.value); setShown(30); }} /><select aria-label="Watchlist status filter" className={`${inputClass} w-auto`} value={status} onChange={e => setStatus(e.target.value)}><option value="all">All statuses</option>{watchStatuses.map(s => <option key={s}>{s}</option>)}</select><button className={buttonClass} aria-expanded={picker} onClick={() => setPicker(v => !v)}>Columns</button><button className={buttonClass} aria-expanded={filters} onClick={() => setFilters(v => !v)}>Filters</button><button className={buttonClass} onClick={() => { setSort(null); setRanges([]); setQuery(''); setStatus('all'); }}>Reset filters & sort</button></div>
      {picker && <div className="rounded-xl bg-secondary/40 p-3"><div className="grid gap-2 sm:grid-cols-3">{marketColumns.map(c => <label key={c.key} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={columns.includes(c.key)} disabled={columns.length === 1 && columns.includes(c.key)} onChange={e => setColumns(v => e.target.checked ? [...v,c.key] : v.filter(k => k !== c.key))} />{c.label}</label>)}</div><button className={`${buttonClass} mt-3`} onClick={() => setColumns(defaultMarketColumns)}>Reset columns</button></div>}
      {filters && <div className="space-y-3 rounded-xl bg-secondary/40 p-3"><button className={buttonClass} disabled={ranges.length >= 8} onClick={() => setRanges(v => [...v,{ metric:'change24hPercent',min:'',max:'' }])}>Add metric filter</button>{ranges.map((r,i) => <div key={i} className="flex flex-wrap gap-2"><select aria-label={`Watchlist filter ${i+1} metric`} className={`${inputClass} w-auto`} value={r.metric} onChange={e => setRanges(v => v.map((p,n) => n === i ? {...p,metric:e.target.value as MarketRange['metric']} : p))}>{marketColumns.map(c => <option key={c.key} value={c.key}>{c.label}</option>)}</select>{(['min','max'] as const).map(bound => <input key={bound} type="number" step="any" aria-label={`Watchlist filter ${i+1} ${bound}`} placeholder={bound === 'min' ? 'Minimum' : 'Maximum'} className={`${inputClass} w-28`} value={r[bound]} onChange={e => setRanges(v => v.map((p,n) => n === i ? {...p,[bound]:e.target.value} : p))} />)}<button className={buttonClass} onClick={() => setRanges(v => v.filter((_,n) => n !== i))}>Remove filter</button>{invalidRange(r) && <p role="alert" className="w-full text-xs text-warning">Minimum must be at or below maximum.</p>}</div>)}<p className="text-[10px] text-muted-foreground">Filters combine. Prices/caps/volume are USD; 5 in a change filter means 5%. Missing values are excluded by active bounds.</p></div>}
      <label className="flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={archived} onChange={e => { setArchived(e.target.checked); setEditing(''); }} />Archived assets</label></div>}
    {(notice || store.error) && <p role="status" className="px-4 pb-3 text-xs text-warning">{store.error || notice}</p>}
    <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-y border-border/40 bg-secondary/20 text-[10px] text-muted-foreground"><tr>{[{ key:'name' as const,label:'Asset' },...selectedColumns].map(c => <th key={c.key} className={`whitespace-nowrap px-4 py-2.5 font-normal ${c.key === 'name' ? '' : 'text-right'}`} aria-sort={sort === c.key ? descending ? 'descending' : 'ascending' : undefined}><button disabled={compact} aria-label={`Sort watchlist by ${c.label}`} onClick={() => chooseSort(c.key)}>{c.label}{!compact && (sort === c.key ? descending ? ' ↓' : ' ↑' : ' ↕')}</button></th>)}{!compact && <><th className="px-4 py-2 font-normal">Status / note</th><th className="px-4 py-2 font-normal">Actions</th></>}</tr></thead><tbody>{visible.map(r => <tr key={r.watchKey} className="border-b border-border/30 last:border-0 hover:bg-secondary/20"><td className="px-4 py-3"><a className="block min-w-[140px] font-medium hover:text-primary" href={watchHref(r.entry.asset)} target={r.entry.asset.provider === 'coingecko' ? '_blank' : undefined} rel={r.entry.asset.provider === 'coingecko' ? 'noreferrer' : undefined}>{r.name}</a><span className="mt-1 block text-[10px] text-muted-foreground">{r.symbol} · {watchProviderNames[r.entry.asset.provider]}</span>{!compact && <span className="block text-[9px] text-muted-foreground">{r.entry.asset.id}</span>}</td>{selectedColumns.map(c => <td key={c.key} className="whitespace-nowrap px-4 py-3 text-right tabular-nums" title={r.sourceUpdatedAt ? `Quote observed ${r.sourceUpdatedAt}` : 'Quote observation time unavailable'}>{c.kind === 'change' ? <Change value={r[c.key]} /> : c.kind === 'price' ? price(r[c.key]) : c.kind === 'money' ? money(r[c.key]) : r[c.key] ?? '—'}</td>)}{!compact && <><td className="px-4 py-3"><span className="whitespace-nowrap text-[10px]">{r.entry.status}</span>{r.entry.notes && <p className="mt-1 max-w-[240px] truncate text-[10px] text-muted-foreground" title={r.entry.notes}>{r.entry.notes}</p>}</td><td className="whitespace-nowrap px-4 py-3"><button disabled={!store.ready} className="mr-3 text-primary" aria-label={`Edit ${r.name} watchlist note`} onClick={() => { setEditing(r.watchKey); setBase(r.entry.updatedAt); setNotes(r.entry.notes); setEditStatus(r.entry.status); setNotice(''); }}>Edit</button><button disabled={!store.ready} className="text-muted-foreground" aria-label={`${archived ? 'Restore' : 'Archive'} ${r.name} from watchlist`} onClick={() => archive(r.watchKey,!archived)}>{archived ? 'Restore' : 'Archive'}</button></td></>}</tr>)}</tbody></table></div>
    {!visible.length && <p className="p-5 text-xs text-muted-foreground">{list.entries.length ? 'No assets match this view.' : 'Add assets from Discovery or paste a token list.'}</p>}
    {!compact && <div className="flex items-center gap-3 px-4 py-3 text-[10px] text-muted-foreground"><span>Showing {visible.length} of {filtered.length}</span>{filtered.length > shown && <button className={buttonClass} onClick={() => setShown(v => v+30)}>Show more</button>}</div>}
    {editing && <form onSubmit={save} className="space-y-3 border-t border-border/50 p-4"><h3 className="text-sm font-medium">Edit watchlist entry</h3><label className="block text-xs">Research status<select className={`${inputClass} mt-1.5`} value={editStatus} onChange={e => setEditStatus(e.target.value as typeof editStatus)}>{watchStatuses.map(s => <option key={s}>{s}</option>)}</select></label><label className="block text-xs">Watchlist note<textarea maxLength={20000} rows={4} className={`${inputClass} mt-1.5`} value={notes} onChange={e => setNotes(e.target.value)} /></label><div className="flex gap-3"><button className={buttonClass} disabled={!store.ready}>Save note</button><button type="button" className={buttonClass} onClick={() => setEditing('')}>Cancel</button></div></form>}
    <p className="px-4 pb-3 text-[10px] text-muted-foreground">{compact ? 'Saved in this browser · prices outside connected coverage stay blank.' : 'Same-provider snapshots only. Prices outside connected coverage stay blank. 4h/12h history is not loaded for watchlists; no sentiment/mindshare feed.'}</p>
    <details className="border-t border-border/40 px-4 py-3 text-xs text-muted-foreground"><summary className="cursor-pointer">Quote sources & freshness</summary>{list.entries.some(e => e.asset.provider === 'coinmarketcap') && <FeedNote feed={cmc} source="CMC · top 100 snapshot" url="https://coinmarketcap.com/" />}{list.entries.some(e => e.asset.provider === 'coinpaprika') && <FeedNote feed={paprika} source="CoinPaprika · market snapshot" url="https://coinpaprika.com/" />}{list.entries.some(e => e.asset.provider === 'coingecko') && <FeedNote feed={gecko} source="CoinGecko · trending snapshot" url="https://www.coingecko.com/en/highlights/trending-crypto" />}</details>
  </Card>;
}
