'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Card, PageHeader } from '@/components/shared';
import { buttonClass, inputClass } from '@/components/projects/fields';
import { ProjectDirectory } from '@/components/projects/directory';
import { useFeed, type Feed } from '@/components/dashboard/use-feed';
import { PersonalPanel } from '@/components/dashboard/panels';
import type { MarketQuote } from '@/services/core/types';
import type { DiscoverySnapshot } from '@/lib/discovery';
import { makeWatchlist, mergeWatchlistBackup, restoreWatchlist, watchCatalog } from '@/lib/watchlists';
import { useWatchlists } from './store';
import { WatchTable } from './table';
import { WatchImport } from './import-preview';
export function WatchlistsWorkspace() {
  const store = useWatchlists(); const [active, setActive] = useState('research'); const [name, setName] = useState(''); const [rename, setRename] = useState<string | null>(null); const [adding, setAdding] = useState(false); const [paste, setPaste] = useState(false); const [notice, setNotice] = useState(''); const fileInput = useRef<HTMLInputElement>(null); const [revision,setRevision] = useState(0);
  const cmc = useFeed<MarketQuote[]>('/api/data/assets?provider=coinmarketcap', revision, 300); const paprika = useFeed<MarketQuote[]>('/api/data/assets', revision); const gecko = useFeed<DiscoverySnapshot>('/api/data/discovery?source=coingecko&kind=trending', revision, 900);
  const list = store.file.lists.find(l => l.id === active && !l.archived); const lists = store.file.lists.filter(l => !l.archived);
  useEffect(() => { if (store.ready) setActive(store.file.selectedId ?? 'research');
    // Restore the selected list after the workspace initially loads.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [store.ready]);
  function select(id: string) { setActive(id); setPaste(false); setRename(null); setNotice(''); }
  function create(e: React.FormEvent) { e.preventDefault(); const id = crypto.randomUUID(); const now = new Date().toISOString(); if (store.commit(f => ({ ...f, selectedId:f.selectedId ?? id, lists:[...f.lists,makeWatchlist(name,id,now)] }))) { select(id); setAdding(false); setName(''); } }
  function archive() { if (!list) return; if (store.commit(f => ({ ...f, selectedId:f.selectedId === list.id ? null : f.selectedId, lists:f.lists.map(l => l.id === list.id ? {...l,archived:true,updatedAt:new Date().toISOString()} : l) }))) { select('research'); setNotice('List archived. Restore it below whenever needed.'); } }
  return <div className="space-y-4"><PageHeader title="Watchlists"><div className="flex flex-wrap gap-2"><button className={buttonClass} disabled={!store.ready} onClick={() => setAdding(v => !v)}>New list</button><button className={buttonClass} onClick={store.exportFile}>Backup lists</button><button className={buttonClass} disabled={!store.ready} onClick={() => fileInput.current?.click()}>Restore backup</button><button className={buttonClass} onClick={() => setRevision(v => v+1)}>Refresh prices</button></div></PageHeader>
    <input type="file" accept=".json,application/json" className="hidden" aria-label="Restore watchlist backup" ref={fileInput} onChange={async e => { const f = e.target.files?.[0]; if (!f) return; try { if (f.size > 10000000) throw Error('Choose a watchlist backup under 10 MB.'); const raw = await f.text(); if (store.commit(current => mergeWatchlistBackup(current,raw))) setNotice('Backup restored. Existing list IDs were kept unchanged; colliding names were renamed.'); } catch { setNotice('Invalid watchlist backup. Existing lists were not changed.'); } e.target.value = ''; }} />
    <p className="text-[10px] text-muted-foreground">Named lists are saved in this browser and backed up separately from research. Cloud sync is not connected for named lists.</p>
    {(store.error || notice) && <div role="status" className="flex flex-wrap items-center gap-3 rounded-xl border border-border p-3 text-xs text-warning"><span>{store.error || notice}</span>{store.error && <button className={buttonClass} onClick={store.reload}>Reload lists</button>}</div>}
    {adding && <Card className="p-4"><form onSubmit={create} className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-xs">List name<input required maxLength={60} className={`${inputClass} mt-1.5`} placeholder="e.g. Core Holdings, RWA, Ecosystems" value={name} onChange={e => setName(e.target.value)} /></label><button className={buttonClass} disabled={!store.ready || !name.trim()}>Create list</button></form></Card>}
    <div className="flex flex-wrap items-center gap-3"><select aria-label="Choose watchlist" className={`${inputClass} max-w-full sm:w-64`} value={list?.id ?? 'research'} onChange={e => select(e.target.value)}><option value="research">Research watchlist</option>{lists.map(l => <option value={l.id} key={l.id}>{l.name} ({l.entries.filter(e => !e.archived).length})</option>)}</select>{list && <><button className={buttonClass} disabled={!store.ready} onClick={() => setPaste(v => !v)}>Paste token list</button><button className={buttonClass} disabled={!store.ready || store.file.selectedId === list.id} onClick={() => { if (store.commit(f => ({...f,selectedId:list.id}))) setNotice('Dashboard watchlist updated.'); }}>Show on dashboard</button><button className={buttonClass} onClick={() => setRename(list.name)}>Rename</button><button className={buttonClass} disabled={!store.ready} onClick={archive}>Archive list</button><Link className="text-xs text-primary" href="/markets">Add from Discovery →</Link></>}{!list && <button className={buttonClass} disabled={!store.ready || !store.file.selectedId} onClick={() => store.commit(f => ({...f,selectedId:null}))}>Show research watchlist on dashboard</button>}</div>
    {list && rename !== null && <form className="flex flex-wrap gap-2" onSubmit={e => { e.preventDefault(); if (store.commit(f => ({...f,lists:f.lists.map(l => l.id === list.id ? {...l,name:rename?.trim() ?? '',updatedAt:new Date().toISOString()} : l)}))) setRename(null); }}><input aria-label="Rename watchlist" required maxLength={60} className={`${inputClass} min-w-0 sm:w-64`} value={rename} onChange={e => setRename(e.target.value)} /><button className={buttonClass} disabled={!store.ready}>Save name</button><button type="button" className={buttonClass} onClick={() => setRename(null)}>Cancel</button></form>}
    {list ? <><WatchTable key={list.id} list={list} cmc={cmc} paprika={paprika} gecko={gecko} />{paste && <WatchImport key={`import:${list.id}`} listId={list.id} catalog={watchCatalog(cmc.data ?? [],paprika.data ?? [],gecko.data)} loading={cmc.loading || paprika.loading || gecko.loading} />}</> : <><p className="text-xs text-muted-foreground">Your existing research watchlist is kept below. Create named lists to organize exact provider assets without changing project research or positions.</p><ProjectDirectory initialStatus="Watching" embedded /></>}
    {store.file.lists.some(l => l.archived) && <Card className="p-4"><details><summary className="cursor-pointer text-xs">Archived lists</summary><div className="mt-3 space-y-3">{store.file.lists.filter(l => l.archived).map(l => <div className="flex flex-wrap items-center justify-between gap-3 text-xs" key={l.id}><span className="break-words">{l.name} · {l.entries.length} saved entries</span><button className={buttonClass} disabled={!store.ready} onClick={() => store.commit(f => restoreWatchlist(f,l.id,new Date().toISOString()))}>Restore {l.name}</button></div>)}</div></details></Card>}
  </div>;
}
export function WatchlistPanel({ cmc, paprika }: { cmc: Feed<MarketQuote[]>; paprika: Feed<MarketQuote[]> }) {
  const store = useWatchlists(); const list = store.file.lists.find(l => l.id === store.file.selectedId && !l.archived);
  const gecko = useFeed<DiscoverySnapshot>('/api/data/discovery?source=coingecko&kind=trending', 0, 1200, !!list?.entries.some(e => !e.archived && e.asset.provider === 'coingecko'));
  return <div className="min-w-0 space-y-2"><label className="flex flex-wrap items-center gap-2 text-[10px] text-muted-foreground">Dashboard watchlist<select aria-label="Dashboard watchlist" className={`${inputClass} w-auto max-w-full text-xs`} disabled={!store.ready} value={list?.id ?? 'research'} onChange={e => store.commit(f => ({...f,selectedId:e.target.value === 'research' ? null : e.target.value}))}><option value="research">Research watchlist</option>{store.file.lists.filter(l => !l.archived).map(l => <option value={l.id} key={l.id}>{l.name}</option>)}</select><Link href="/watchlists" className="text-primary">Manage →</Link></label>{store.error && <p role="status" className="text-xs text-warning">{store.error}</p>}{list ? <WatchTable key={list.id} compact list={list} cmc={cmc} paprika={paprika} gecko={gecko} /> : <PersonalPanel quotes={paprika.data ?? []} />}</div>;
}
