'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/components/auth/provider';
import { useProjects } from '@/components/projects/store';
import { Card } from '@/components/shared';
import { inputClass, buttonClass } from '@/components/projects/fields';
import { parseUtcMinute, chartMarkets, chartIntervals, chartDatasetSchema, chartPlanSchema, parseChartPlans, saveChartPlan, mergeChartPlans, type ChartPlan, type Drawing, type ChartMarket, type ChartInterval } from '@/lib/chart-plans';
import { PlanChart } from './plan-chart';
import type { ServiceResult } from '@/services/core/types';
import type { ChartDataset } from '@/lib/chart-plans';
export function ChartPlans({ initialProject='' }: {initialProject?:string}) {const auth=useAuth();const scope=auth.session?.user.id??'browser';return <Editor key={scope} scope={scope} initialProject={initialProject}/>;}
function Editor({scope,initialProject}:{scope:string;initialProject:string}) {
  const projects=useProjects(); const key=`atlas.chart-plans.v1:${scope}`;
  const [plans,setPlans]=useState<ChartPlan[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [backup,setBackup]=useState<{url:string;name:string}|null>(null);
  useEffect(()=>()=>{if(backup)URL.revokeObjectURL(backup.url);},[backup]);
  function download(text:string,name:string){setBackup({url:URL.createObjectURL(new Blob([text],{type:'application/json'})),name});setNotice('Backup ready. Select Save chart backup file.');}
  const expected=useRef<string|null>(null);const [plan,setPlan]=useState<ChartPlan|null>(null),[saved,setSaved]=useState('');
  const [market,setMarket]=useState<ChartMarket>('BTCUSDT'),[interval,setInterval]=useState<ChartInterval>('1d'),[busy,setBusy]=useState(false);
  const [tool,setTool]=useState<Drawing['kind']|'inspect'>('inspect'),[first,setFirst]=useState<Drawing['a']|null>(null);
  const [drawingId,setDrawingId]=useState(''),[kind,setKind]=useState<Drawing['kind']>('level'),[label,setLabel]=useState(''),[price,setPrice]=useState(''),[at,setAt]=useState(''),[endPrice,setEndPrice]=useState(''),[endAt,setEndAt]=useState('');
  const dirty=!!plan&&JSON.stringify(plan)!==saved;
  function read(){try{const raw=localStorage.getItem(key);const file=parseChartPlans(raw);setPlans(file.plans);expected.current=raw;setReady(true);setError('');}catch{setReady(false);setError('Saved plans could not be read. Export the stored backup before making changes.');}}
  useEffect(()=>{read();const changed=(e:StorageEvent)=>{if(e.key===key)setError('Saved plans changed in another tab. Your current draft is kept. Export the draft before reloading saved plans.');};window.addEventListener('storage',changed);return()=>window.removeEventListener('storage',changed);
  // Scope remounts this editor; never reload stored plans over an active draft.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[key]);
  useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};const link=(e:MouseEvent)=>{const a=(e.target as HTMLElement).closest('a');if(dirty&&a&&!a.download&&!a.target&&!window.confirm('Leave this unsaved chart plan?'))e.preventDefault();};window.addEventListener('beforeunload',before);document.addEventListener('click',link,true);return()=>{window.removeEventListener('beforeunload',before);document.removeEventListener('click',link,true);};},[dirty]);
  function replace(next:ChartPlan){setPlan(next);setSaved(JSON.stringify(next));setMarket(next.market);setInterval(next.interval);setFirst(null);setTool('inspect');setDrawingId('');setNotice('Saved snapshot opened. Refresh candles explicitly when you want newer data.');setError('');}
  async function load(refresh=false){
    if(!refresh&&dirty&&!window.confirm('Start another chart and discard this unsaved draft?'))return;
    setBusy(true);setError('');setNotice('');
    try{const response=await fetch(`/api/data/candles?market=${market}&interval=${interval}`);const result=await response.json() as ServiceResult<ChartDataset>;
      if(!result.ok)throw Error(result.error.message);const dataset=chartDatasetSchema.parse(result.data);
      if(dataset.market!==market||dataset.interval!==interval)throw Error('Unexpected chart dataset.');
      const now=new Date().toISOString();
      if(refresh&&plan)setPlan({...plan,dataset,fetchedAt:result.meta.fetchedAt});
      else{setPlan({id:crypto.randomUUID(),projectId:initialProject,name:'',market,interval,style:'candles',indicators:{sma50:true,sma200:false,ema50:false,rsi14:false,volume:true},drawings:[],thesis:'',invalidation:'',dataset,fetchedAt:result.meta.fetchedAt,createdAt:now,updatedAt:now});setSaved('');setFirst(null);setDrawingId('');setAt(new Date(dataset.candles[dataset.candles.length-1].time).toISOString().slice(0,16));setTool('inspect');}
      setNotice(`${dataset.candles.length} closed candles loaded · ${result.meta.cache==='stale'?'Stale cached data; upstream refresh failed':result.meta.cache==='fresh'?'Cached snapshot':'New snapshot'}. Latest close ${new Date(dataset.candles[dataset.candles.length-1].closeTime).toISOString()}.`);
    }catch(cause){setError(cause instanceof Error?cause.message:'Candles unavailable.');}finally{setBusy(false);}
  }
  function update(patch:Partial<ChartPlan>){if(plan)setPlan({...plan,...patch});setNotice('');}
  function save(){if(!plan||!ready)return;try{if(!projects.projects.some(p=>p.id===plan.projectId))throw Error('Choose an existing project before saving.');const next=chartPlanSchema.parse({...plan,updatedAt:new Date().toISOString()});const file=saveChartPlan(localStorage.getItem(key),expected.current,next,saved ? (JSON.parse(saved) as ChartPlan).updatedAt : undefined);const raw=JSON.stringify(file);localStorage.setItem(key,raw);expected.current=raw;setPlans(file.plans);setPlan(next);setSaved(JSON.stringify(next));setNotice('Chart plan saved in this browser.');setError('');}catch(cause){setError(cause instanceof Error?cause.message:'Save failed. Your draft is kept.');}}
  function point(p:Drawing['a']){if(!plan||busy||tool==='inspect')return;if(plan.drawings.length>=50){setError('A plan can hold up to 50 drawings.');return;}if(tool==='trend'&&!first){setFirst(p);setNotice('Choose a second point at a different time.');return;}if(tool==='trend'&&first?.time===p.time)return;update({drawings:[...plan.drawings,{id:crypto.randomUUID(),kind:tool,label:'',a:first??p,b:tool==='trend'?p:null}]});setFirst(null);}
  function drawingForm(){if(!plan)return;try{const a={time:parseUtcMinute(at),price:Number(price)},b=kind==='trend'?{time:parseUtcMinute(endAt),price:Number(endPrice)}:null;const drawing={id:drawingId||crypto.randomUUID(),kind,label,a,b};const next=chartPlanSchema.parse({...plan,name:plan.name||'Draft',projectId:plan.projectId||'draft',drawings:drawingId?plan.drawings.map(d=>d.id===drawingId?drawing:d):[...plan.drawings,drawing]});update({drawings:next.drawings});setDrawingId('');setLabel('');setError('');}catch{setError('Use a positive price and valid UTC date/time. Trend lines need two different times; maximum 50 drawings.');}}
  function editDrawing(d:Drawing){setDrawingId(d.id);setKind(d.kind);setLabel(d.label);setPrice(String(d.a.price));setAt(new Date(d.a.time).toISOString().slice(0,16));setEndPrice(d.b?String(d.b.price):'');setEndAt(d.b?new Date(d.b.time).toISOString().slice(0,16):'');}
  const field=(name:string,value:string,onChange:(v:string)=>void,type='text')=><label className="block space-y-1 text-xs text-muted-foreground">{name}<input className={inputClass} type={type==='datetime-local'?'text':type} placeholder={type==='datetime-local'?'YYYY-MM-DD HH:mm':undefined} maxLength={type==='datetime-local'?16:100} step={type==='number'?'any':undefined} value={value} onChange={e=>onChange(e.target.value)}/></label>;
  return <fieldset disabled={busy} className="min-w-0 space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Saved chart plans</h2><span className="text-xs text-muted-foreground">{dirty?'Unsaved draft':'Browser-local plans'} · {plans.length}/20</span></div>
    <p className="text-xs text-muted-foreground">Keep editable scenarios with a project. Plans include a candle snapshot and their own backup; they do not sync with cloud research. Prices are Binance spot USDT, not USD.</p>
    <Card className="space-y-3 p-4"><div className="flex flex-wrap items-end gap-3"><label className="text-xs text-muted-foreground">Saved plan<select aria-label="Open saved plan" className={inputClass} value="" onChange={e=>{const found=plans.find(p=>p.id===e.target.value);if(found&&(!dirty||window.confirm('Replace the unsaved draft with this saved plan?')))replace(found);}}><option value="">Choose a saved plan</option>{plans.filter(p=>!initialProject||p.projectId===initialProject).map(p=><option key={p.id} value={p.id}>{p.name} · {projects.projects.find(x=>x.id===p.projectId)?.name??'Former project'} · {p.market} {p.interval}</option>)}</select></label><button className={buttonClass} onClick={read}>Reload saved plans</button><button className={buttonClass} onClick={()=>{try{download(localStorage.getItem(key)??'{"version":1,"plans":[]}','atlas-chart-plans.json');}catch{setError('Backup could not be read.');}}}>Backup plans</button><label className={`${buttonClass} cursor-pointer`}>Restore plans<input className="sr-only" type="file" accept="application/json,.json" disabled={!ready||busy} onChange={async e=>{const input=e.currentTarget,file=input.files?.[0];if(!file)return;try{if(file.size>4000000)throw Error('Backup is too large.');const incoming=await file.text();const current=localStorage.getItem(key);if(current!==expected.current)throw Error('Saved plans changed. Reload saved plans before restoring.');const next=mergeChartPlans(current,incoming);const raw=JSON.stringify(next);localStorage.setItem(key,raw);expected.current=raw;setPlans(next.plans);setNotice('Backup restored. Existing plans were kept.');setError('');}catch(cause){setError(cause instanceof Error?cause.message:'Restore failed.');}finally{input.value='';}}}/></label></div></Card>
    {backup&&<a className="block text-sm text-primary underline" href={backup.url} download={backup.name}>Save chart backup file</a>}
    <Card className="flex flex-wrap items-end gap-3 p-4"><label className="text-xs text-muted-foreground">Market<select aria-label="Plan market" className={inputClass} value={market} disabled={busy} onChange={e=>setMarket(e.target.value as ChartMarket)}>{chartMarkets.map(m=><option key={m}>{m}</option>)}</select></label><label className="text-xs text-muted-foreground">Timeframe<select aria-label="Plan timeframe" className={inputClass} value={interval} disabled={busy} onChange={e=>setInterval(e.target.value as ChartInterval)}>{chartIntervals.map(i=><option key={i}>{i}</option>)}</select></label><button className={buttonClass} disabled={busy} onClick={()=>void load()}>{busy?'Loading…':'New chart plan'}</button></Card>
    {(error||notice)&&<p role="status" className={`rounded-lg border p-3 text-sm ${error?'text-destructive':'text-primary'}`}>{error||notice}</p>}
    {plan&&<><Card className="space-y-4 p-4"><div className="grid gap-3 sm:grid-cols-2">{field('Plan name',plan.name,v=>update({name:v}))}<label className="text-xs text-muted-foreground">Attach to project<select aria-label="Attach to project" className={inputClass} value={plan.projectId} onChange={e=>update({projectId:e.target.value})}><option value="">Choose project</option>{projects.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><p className="text-xs text-muted-foreground">Attaching a chart records your chosen research context; it does not establish that this venue pair is the project’s token.</p><div className="flex flex-wrap gap-3"><select aria-label="Chart style" className={`${inputClass} w-auto`} value={plan.style} onChange={e=>update({style:e.target.value as ChartPlan['style']})}><option value="candles">Candles</option><option value="line">Close line</option></select>{(['sma50','sma200','ema50','rsi14','volume'] as const).map(k=><label key={k} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={plan.indicators[k]} onChange={e=>update({indicators:{...plan.indicators,[k]:e.target.checked}})}/>{({sma50:'SMA 50',sma200:'SMA 200',ema50:'EMA 50',rsi14:'RSI 14',volume:'Volume'})[k]}</label>)}</div><div className="flex flex-wrap gap-2">{(['inspect','level','trend','note'] as const).map(t=><button key={t} className={`${buttonClass} ${tool===t?'bg-primary/15 text-primary':''}`} aria-pressed={tool===t} onClick={()=>{setTool(t);setFirst(null);}}>{({inspect:'Inspect',level:'Draw level',trend:'Draw trend line',note:'Add annotation'})[t]}</button>)}</div><p className="text-xs text-muted-foreground">Click the chart to place drawings, or enter exact coordinates below. Latest 120 candles shown; indicators use the full saved history. Out-of-view drawings remain in the list.</p><PlanChart plan={plan} tool={tool} onPoint={point}/><p className="text-xs text-muted-foreground">Snapshot fetched {new Date(plan.fetchedAt).toLocaleString()} · latest candle closes {new Date(plan.dataset.candles[plan.dataset.candles.length-1].closeTime).toLocaleString()} · UTC axis. Refreshing preserves time/price coordinates.</p><button className={buttonClass} disabled={busy||market!==plan.market||interval!==plan.interval} onClick={()=>void load(true)}>Refresh candles for this plan</button></Card>
    <Card className="space-y-3 p-4"><h3 className="font-semibold">{drawingId?'Edit drawing':'Add drawing by coordinates'}</h3><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs text-muted-foreground">Drawing type<select className={inputClass} value={kind} onChange={e=>setKind(e.target.value as Drawing['kind'])}><option value="level">Horizontal level</option><option value="trend">Trend line</option><option value="note">Annotation</option></select></label>{field('Drawing label',label,setLabel)}{field('Price (USDT)',price,setPrice,'number')}{field('Time (UTC)',at,setAt,'datetime-local')}{kind==='trend'&&<>{field('End price (USDT)',endPrice,setEndPrice,'number')}{field('End time (UTC)',endAt,setEndAt,'datetime-local')}</>}</div><button className={buttonClass} onClick={drawingForm}>{drawingId?'Update drawing':'Add drawing'}</button>{drawingId&&<button className={`${buttonClass} ml-2`} onClick={()=>setDrawingId('')}>Cancel drawing edit</button>}<ul className="space-y-2">{plan.drawings.map(d=><li key={d.id} className="flex flex-wrap items-center justify-between gap-2 border-t pt-2 text-xs"><span className="break-all">{d.label||d.kind} · {d.a.price} USDT · {new Date(d.a.time).toISOString().slice(0,16).replace('T',' ')}</span><span className="flex gap-3"><button onClick={()=>editDrawing(d)} className="text-primary" aria-label={`Edit ${d.label||d.kind}`}>Edit</button><button className="text-muted-foreground" onClick={()=>update({drawings:plan.drawings.filter(x=>x.id!==d.id)})} aria-label={`Remove ${d.label||d.kind}`}>Remove from draft</button></span></li>)}</ul></Card>
    <Card className="space-y-3 p-4"><label className="block text-xs text-muted-foreground">Scenario thesis<textarea className={`${inputClass} min-h-24`} maxLength={10000} value={plan.thesis} onChange={e=>update({thesis:e.target.value})}/></label><label className="block text-xs text-muted-foreground">Scenario invalidation<textarea className={`${inputClass} min-h-20`} maxLength={10000} value={plan.invalidation} onChange={e=>update({invalidation:e.target.value})}/></label><div className="flex flex-wrap gap-2"><button className={`${buttonClass} bg-primary text-primary-foreground`} disabled={!ready||busy||!projects.ready} onClick={save}>Save chart plan</button><button className={buttonClass} onClick={()=>{try{download(JSON.stringify({version:1,plans:[chartPlanSchema.parse(plan)]},null,2),'atlas-chart-draft.json');}catch{setError('Give the draft a name and project before exporting it.');}}}>Export current draft</button>{plan.projectId&&<Link className={buttonClass} href={`/projects/${plan.projectId}`}>Open project</Link>}</div></Card></>}
  </fieldset>;
}
