'use client';
import { useState } from 'react';
import { WatchlistPanel } from '@/components/watchlists/workspace';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { RefreshCw } from 'lucide-react';
import { Card } from '@/components/shared';
import { DiscoveryTable, CmcAssetDetails } from './cmc-discovery';
import { CmcSentimentPanel } from './cmc-sentiment';
import { MarketStructure } from './market-structure';
import { structureSummary } from '@/lib/market-dashboard';
import { buttonClass } from '@/components/projects/fields';
import type { MarketQuote, GlobalMarket } from '@/services/core/types';
import type { Sentiment } from '@/services/intelligence/types';
import { useFeed } from './use-feed';
import { Panel, Change, MarketTable, MacroPanel, NewsPanel, PersonalPanel, TrendingPanel, ChainPanel, SupplyPanel, RevenuePanel, DexPanel, SentimentPanel, CalendarPanel, FeedNote, HistoryChart, money, price } from './panels';
function Header({ title, refresh }: { title: string; refresh: () => void }) {
  return <div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-semibold tracking-tight">{title}</h1><div className="flex items-center gap-3"><Link href="/data-sources" className="text-[11px] text-muted-foreground hover:text-foreground">Data coverage</Link><button className={buttonClass} onClick={refresh}><RefreshCw size={13} />Refresh</button></div></div>;
}
function Coverage() {
  return <Card className="px-4 py-3"><details><summary className="cursor-pointer text-xs text-muted-foreground">Additional coverage · derivatives, X, RWA, global liquidity & economic events</summary><div className="mt-3 grid gap-3 text-xs sm:grid-cols-2"><p className="text-muted-foreground">Funding, open interest and liquidations are not connected. <a className="text-primary" href="https://www.coinglass.com/" target="_blank" rel="noreferrer">CoinGlass ↗</a></p><p className="text-muted-foreground">Trending searches are from CoinGecko. X posts and social metrics are not connected.</p><p className="text-muted-foreground">TVL and stablecoin supply are connected; RWA asset classes and trading access remain planned. <a className="text-primary" href="https://app.rwa.xyz/" target="_blank" rel="noreferrer">RWA.xyz ↗</a></p><p className="text-muted-foreground">Macro currently covers US series. Global rates, a multi-country money composite and automated economic events remain planned.</p></div></details></Card>;
}
function Group({ title, href, children }: { title: string; href?: string; children: React.ReactNode }) {
  return <section className="min-w-0 space-y-3" aria-label={title}><div className="flex items-center justify-between"><h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{title}</h2>{href && <Link href={href} className="text-[11px] text-primary">Explore ↗</Link>}</div>{children}</section>;
}
function OverviewMetric({ label, value, href, change, note }: { label: string; value: string; href: string; change?: number | null; note?: string }) {
  return <Link href={href} className="min-w-0 rounded-xl bg-secondary/35 p-2 hover:bg-secondary/60"><p className="text-[10px] text-muted-foreground">{label}</p><div className="mt-1.5 flex flex-wrap items-baseline gap-2"><span className="text-lg font-semibold tabular-nums">{value}</span>{change != null && <Change value={change} />}</div>{note && <p className="mt-1 text-[10px] text-muted-foreground">{note}</p>}</Link>;
}
export function MarketDashboard() {
  const [revision, setRevision] = useState(0);
  const assets = useFeed<MarketQuote[]>('/api/data/assets', revision);
  const cmcAssets = useFeed<MarketQuote[]>('/api/data/assets?provider=coinmarketcap', revision, 4500);
  const global = useFeed<GlobalMarket>('/api/data/global?provider=auto', revision, 450);
  const quotes = assets.data ?? []; const btc = quotes.find(a => a.asset.coinpaprikaId === 'btc-bitcoin'); const eth = quotes.find(a => a.asset.coinpaprikaId === 'eth-ethereum');
  const g = global.data; const globalProvider = global.result?.ok ? global.result.meta.provider : null; const globalName = globalProvider === 'coinmarketcap' ? 'CoinMarketCap' : globalProvider === 'coinpaprika' ? 'CoinPaprika' : 'Global market';
  return <div className="space-y-5"><Header title="Dashboard" refresh={() => setRevision(v => v + 1)} />
    <div className="grid items-start gap-4 xl:grid-cols-12"><div className="xl:col-span-8"><Panel title="Market status" href="/markets"><div className="grid grid-cols-2 gap-2 px-4 pb-3 md:grid-cols-3"><OverviewMetric label="Bitcoin" value={price(btc?.price)} change={btc?.change24hPercent} href="/markets?asset=btc-bitcoin" note="BTC · 24h" /><OverviewMetric label="Ethereum" value={price(eth?.price)} change={eth?.change24hPercent} href="/markets?asset=eth-ethereum" note="ETH · 24h" /><OverviewMetric label="Crypto market cap" value={money(g?.marketCap)} change={g?.marketCapChange24hPercent} href="/markets" note={`${globalName} universe`} /><OverviewMetric label="24h trading volume" value={money(g?.volume24h)} change={g?.volumeChange24hPercent} href="/markets" /><OverviewMetric label="BTC dominance" value={g?.btcDominancePercent == null ? '—' : `${g.btcDominancePercent.toFixed(2)}%`} href="/market-cycle" /><OverviewMetric label="ETH / BTC" value={eth?.price != null && btc?.price ? (eth.price / btc.price).toFixed(5) : '—'} href="/market-cycle#structure" note="CoinPaprika quote ratio" /></div><div className="grid sm:grid-cols-2"><FeedNote feed={assets} source="CoinPaprika · prices" url="https://coinpaprika.com/" observed={btc?.sourceUpdatedAt} /><FeedNote feed={global} source={`${globalName} · global`} url={globalProvider === 'coinmarketcap' ? 'https://coinmarketcap.com/charts/' : 'https://coinpaprika.com/'} observed={g?.sourceUpdatedAt} /></div></Panel></div>
    <div className="xl:col-span-4"><CmcSentimentPanel revision={revision} /></div></div>
    <StructureSnapshot global={g ?? null} quotes={globalProvider === 'coinpaprika' ? quotes : globalProvider === 'coinmarketcap' ? cmcAssets.data ?? [] : []} source={globalName} />
    <Group title="Discovery" href="/markets"><DiscoveryTable cmc={cmcAssets} paprika={assets} initialLimit={12} /></Group>
    <div className="grid items-start gap-4 lg:grid-cols-3"><MacroPanel revision={revision} /><TrendingPanel revision={revision} /><Panel title="Derivatives & flows"><div className="space-y-2 px-4 pb-4 text-xs"><div className="flex justify-between gap-2 rounded-lg bg-secondary/35 p-2.5"><span className="text-muted-foreground">CMC derivatives volume · 24h</span><span className="tabular-nums">{money(g?.derivativesVolume24h)}</span></div>{['Open interest', 'Funding rates', 'Long / short liquidations', 'ETF flows'].map(label => <div key={label} className="flex justify-between gap-2 rounded-lg bg-secondary/35 p-2.5"><span className="text-muted-foreground">{label}</span><span className="text-[10px] text-muted-foreground">Not connected</span></div>)}<a href="https://www.coinglass.com/" target="_blank" rel="noreferrer" className="block pt-1 text-[11px] text-primary">Open CoinGlass ↗</a></div></Panel></div>
    <Group title="Your markets"><div className="grid items-start gap-4 xl:grid-cols-2"><PersonalPanel quotes={quotes} portfolio /><WatchlistPanel cmc={cmcAssets} paprika={assets} /></div></Group>
    <Group title="News & calendar"><div className="grid items-start gap-4 lg:grid-cols-3"><div className="lg:col-span-2"><NewsPanel revision={revision} /></div><CalendarPanel /></div></Group>
    <Group title="Onchain activity" href="/chains"><OnchainPanel revision={revision} /></Group>
    <Coverage />
  </div>;
}
function StructureSnapshot({ global, quotes, source }: { global: GlobalMarket | null; quotes: MarketQuote[]; source: string }) {
  return <Panel title="Market structure" href="/market-cycle#structure" label="Cap · share of total · 24h cap change"><div className="grid gap-px bg-border/40 sm:grid-cols-2 xl:grid-cols-4">{structureSummary(global, quotes).map(row => <Link href="/market-cycle#structure" key={row.label} className="min-w-0 bg-card px-4 py-3 hover:bg-secondary/30"><p className="text-[11px] text-muted-foreground">{row.label}</p><div className="mt-1 flex items-baseline justify-between gap-2"><span className="text-lg font-semibold tabular-nums">{row.cap !== null && row.estimated ? '≈ ' : ''}{money(row.cap)}</span><Change value={row.change} /></div><div className="mt-1 flex items-center justify-between text-[10px] text-muted-foreground"><span>{row.share === null ? 'Share unavailable' : `${row.share.toFixed(1)}% of total`}</span>{row.change === null && <span>24h unavailable</span>}</div></Link>)}</div><details className="border-t border-border/40 px-4 py-2 text-[10px] text-muted-foreground"><summary className="cursor-pointer">{source} estimates · definitions</summary><p className="mt-2 leading-relaxed">All crypto and its 24h change are provider-reported. Exclusions use the global provider’s BTC/ETH dominance. Matching provider quotes supply top-ten cap and may supplement a missing ETH share when timestamps align within 10 minutes. Quotes from another provider are never mixed. Outside top 10 excludes this provider’s ten ranked assets, including stablecoins. These are not TradingView’s top-125 TOTAL/TOTAL2/TOTAL3/OTHERS indices. Exclusion-basket change history is unavailable; price returns are not substituted for cap changes.</p><Link href="/market-cycle#structure" className="mt-2 block text-primary">Open structure charts & cycle context ↗</Link></details></Panel>;
}
function OnchainPanel({ revision }: { revision: number }) {
  const [view, setView] = useState<'capital' | 'economics'>('capital');
  return <div className="space-y-3"><div className="flex gap-1">{(['capital', 'economics'] as const).map(v => <button key={v} className={`rounded-lg px-3 py-1.5 text-xs ${view === v ? 'bg-secondary font-medium' : 'text-muted-foreground'}`} aria-pressed={view === v} onClick={() => setView(v)}>{v === 'capital' ? 'TVL & stablecoins' : 'Volume & revenue'}</button>)}</div><div className="grid items-start gap-4 lg:grid-cols-2">{view === 'capital' ? <><ChainPanel revision={revision} /><SupplyPanel revision={revision} /></> : <><DexPanel revision={revision} /><RevenuePanel revision={revision} /></>}</div></div>;
}
export function MarketsPage() {
  const [revision, setRevision] = useState(0);
  const assets = useFeed<MarketQuote[]>('/api/data/assets', revision);
  const cmcAssets = useFeed<MarketQuote[]>('/api/data/assets?provider=coinmarketcap', revision);
  const params = useSearchParams(); const focus = params.get('asset'); const rawCmc = params.get('cmc');
  const cmcFocus = rawCmc && /^[1-9]\d{0,9}$/.test(rawCmc) ? rawCmc : null;
  const selected = focus ? assets.data?.find(q => q.asset.coinpaprikaId === focus) : null;
  const cmcSelected = cmcFocus ? cmcAssets.data?.find(q => q.asset.coinmarketcapId === Number(cmcFocus)) : undefined;
  return <div className="space-y-4"><Header title="Crypto markets" refresh={() => setRevision(v => v + 1)} />
    {rawCmc && !cmcFocus && <p role="alert" className="text-xs text-warning">Invalid CMC asset ID.</p>}
    {cmcFocus && <CmcAssetDetails key={`cmc-details:${cmcFocus}`} id={cmcFocus} quote={cmcSelected} quoteFeed={cmcAssets} revision={revision} />}
    {focus && <Card className="flex flex-wrap items-center justify-between gap-4 p-4"><div><h2 className="font-semibold">{selected?.name ?? 'Asset'}</h2><p className="mt-1 text-xs text-muted-foreground">{selected ? `${selected.symbol} · ${price(selected.price)} · observed ${selected.sourceUpdatedAt ?? 'time unavailable'}` : assets.loading ? 'Loading…' : 'Not present in the current feed.'}</p></div><Link className="text-xs text-primary" href="/markets">Show all assets →</Link></Card>}
    {focus ? <MarketTable feed={{ ...assets, data: assets.data?.filter(q => q.asset.coinpaprikaId === focus) ?? null }} detailed /> : <DiscoveryTable key={`discovery:${cmcFocus ?? 'all'}`} cmc={cmcAssets} paprika={assets} />}
    <div id="trending" className="scroll-mt-4"><TrendingPanel revision={revision} detailed /></div>
  </div>;
}
export function MacroPage() { const [revision, setRevision] = useState(0); return <div className="space-y-4"><Header title="Macro & global markets" refresh={() => setRevision(v => v + 1)} /><MacroPanel revision={revision} detailed /><Card className="p-4 text-xs leading-relaxed text-muted-foreground">Latest available observations, not intraday quotes. PCE/CPI show MoM and YoY changes from seasonally adjusted price indices; charts show index levels. Observation dates are reference periods, not release times. Real yields are inflation-indexed Treasury yields. Henry Hub is US spot gas, not European TTF. The broad US dollar index is trade-weighted, not DXY. M2 here covers the United States only. Effective federal funds is a monthly average, not a central-bank target range. Series may be revised; hover charts to inspect dates and values.</Card><Coverage /></div>; }
export function NewsPage() { const [revision, setRevision] = useState(0); return <div className="space-y-4"><Header title="News & policy" refresh={() => setRevision(v => v + 1)} /><NewsPanel revision={revision} detailed /><Card className="p-4 text-xs text-muted-foreground">Headlines and links from CoinDesk, Cointelegraph, Federal Reserve monetary-policy releases and ECB communications. Open an article for its reporting and context. Broader trade, tariff, political and social coverage is still to be connected.</Card></div>; }
export function ChainsPage() { const [revision, setRevision] = useState(0); return <div className="space-y-4"><Header title="Chains & liquidity" refresh={() => setRevision(v => v + 1)} /><div className="grid items-start gap-4 xl:grid-cols-2"><ChainPanel revision={revision} detailed /><div className="space-y-4"><div id="stablecoins"><SupplyPanel revision={revision} detailed /></div><div id="dex"><DexPanel revision={revision} detailed /></div></div></div><div id="revenue"><RevenuePanel revision={revision} detailed /></div><Card className="p-4 text-xs leading-relaxed text-muted-foreground">TVL, stablecoin supply and trading volume measure different things and are not added together. USD changes include valuation effects; they are not net capital inflows. Revenue definitions vary by protocol. RWA values, access restrictions, chain history and token-holder value capture remain planned.</Card></div>; }
export function PortfolioPage() { const [revision, setRevision] = useState(0); const assets = useFeed<MarketQuote[]>('/api/data/assets', revision); return <div className="space-y-4"><Header title="Portfolio" refresh={() => setRevision(v => v + 1)} /><PersonalPanel quotes={assets.data ?? []} portfolio detailed /><FeedNote feed={assets} source="CoinPaprika · valuation quotes" url="https://coinpaprika.com/" /><Card className="p-4 text-xs text-muted-foreground">Quantities are saved with your research projects and included in backups. An “Owned” status alone does not imply a quantity or cost. Totals exclude unavailable prices and show a subtotal when coverage is incomplete. No exchange, wallet or CMC account is connected.</Card></div>; }
export function CyclePage() { const [revision, setRevision] = useState(0); const assets = useFeed<MarketQuote[]>('/api/data/assets', revision); const sentiment = useFeed<Sentiment>('/api/data/intelligence?feed=sentiment', revision); return <div className="space-y-4"><Header title="Market structure & cycle" refresh={() => setRevision(v => v + 1)} /><div id="structure" className="scroll-mt-4"><MarketStructure detailed /></div><CmcSentimentPanel revision={revision} /><div className="grid items-start gap-4 lg:grid-cols-2"><SentimentPanel feed={sentiment} quotes={assets.data ?? []} /><Card className="p-4"><h2 className="text-sm font-semibold">Bitcoin Fear & Greed · 30 days</h2><HistoryChart points={sentiment.data?.points ?? []} /><FeedNote feed={sentiment} source="Alternative.me" url="https://alternative.me/crypto/fear-and-greed-index/" /></Card></div><Card className="p-4 text-xs leading-relaxed text-muted-foreground">Historical cycle comparisons, broader rotation analysis and editable scenarios remain planned. CMC’s Altcoin Season Index is an observation, not a complete cycle classification. A sentiment value or a calendar date alone does not establish the market’s cycle phase.</Card></div>; }
