'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, CheckCircle2, Download, Plus, RefreshCw, Search, Sunrise, Globe2, BarChart3, PieChart, Bitcoin, Gem } from 'lucide-react';
import { Badge, Card, CardBody, CardHeader, StatCard } from '@/components/shared';
import { useProjects } from '@/components/projects/store';
import { buttonClass, inputClass } from '@/components/projects/fields';
import { newProject } from '@/lib/projects';
import { localDay, displayDay } from '@/lib/research-routine';
import { projectEvents, reviewQueue } from '@/lib/research-desk';
import { formatCurrency, formatPercent, formatPrice, getTrendColor } from '@/lib/format';
import type { GlobalMarket, MarketQuote, ServiceResult } from '@/services/core/types';
import { DataStamp, requestData } from './data';

const currency = (value: number | null | undefined) => value == null ? '—' : formatCurrency(value);
function Change({ value }: { value: number | null | undefined }) {
  return <span className={`font-mono ${value == null ? 'text-muted-foreground' : getTrendColor(value)}`}>{value == null ? '—' : formatPercent(value)}</span>;
}
export function MorningDesk() {
  const store = useProjects();
  const [assets, setAssets] = useState<ServiceResult<MarketQuote[]> | null>(null);
  const [global, setGlobal] = useState<ServiceResult<GlobalMarket> | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [query, setQuery] = useState(''); const [view, setView] = useState<'projects' | 'market'>('projects');
  const [limit, setLimit] = useState(20); const [today, setToday] = useState('');
  useEffect(() => { const tick = () => setToday(localDay()); tick(); const timer = setInterval(tick, 60000); return () => clearInterval(timer); }, []);
  const refresh = useCallback(async () => {
    setBusy(true); setError('');
    try { setAssets(await requestData('/api/data/assets')); } catch { setError('Market snapshot could not load. Your saved research is still available.'); }
    // Space the two distinct endpoints; all asset searches share the same cached feed.
    await new Promise(resolve => setTimeout(resolve, 350));
    try { setGlobal(await requestData('/api/data/global?provider=coinpaprika')); } catch { setError(e => `${e} Global context could not load. Retry when connected.`.trim()); }
    setBusy(false);
  }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const quotes = assets?.ok ? assets.data : [];
  const byId = new Map(quotes.map(a => [a.asset.coinpaprikaId, a]));
  const active = store.projects.filter(p => p.status !== 'Archived');
  const queue = reviewQueue(store.projects, today);
  const due = queue.filter(p => p.due);
  const reviewedToday = active.filter(p => p.review.entries.some(e => localDay(new Date(e.recordedAt)) === today));
  const upcoming = projectEvents(store.projects).filter(e => e.event.date >= today);
  const g = global?.ok ? global.data : null;
  const bitcoin = byId.get('btc-bitcoin'); const ethereum = byId.get('eth-ethereum');
  const q = query.trim().toLowerCase();
  const marketRows = quotes.filter(a => !q || `${a.name} ${a.symbol} ${a.asset.coinpaprikaId}`.toLowerCase().includes(q)).sort((a, b) => (a.rank ?? Infinity) - (b.rank ?? Infinity));
  const projectRows = active.filter(p => !q || `${p.name} ${p.symbol} ${p.narratives.join(' ')}`.toLowerCase().includes(q));
  const sourceDates = quotes.map(a => a.sourceUpdatedAt).filter((d): d is string => Boolean(d));
  const oldest = sourceDates.length ? sourceDates.reduce((a, b) => a < b ? a : b) : null;
  async function add(asset: MarketQuote) {
    if (store.projects.some(p => p.coinpaprikaId === asset.asset.coinpaprikaId)) return;
    const project = { ...newProject(asset.name, asset.symbol), coinpaprikaId: asset.asset.coinpaprikaId!, status: 'Watching' as const };
    if (await store.save(project)) setNotice(`${project.name} added to Watching. Open it to load a profile and start your research.`);
  }
  return <div className="space-y-5">
    <div className="relative pb-1"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-[10px] font-medium uppercase tracking-[0.14em] text-muted-foreground"><Sunrise size={16} /> Atlas research</div><h1 className="text-xl font-medium tracking-tight sm:text-[23px]">Research Desk</h1><p className="mt-2 max-w-2xl text-xs leading-relaxed text-muted-foreground">Scan the market, review your projects, and record what deserves your attention next.</p><p className="mt-2 text-[10px] text-muted-foreground">{today ? displayDay(today) : 'Your daily research workspace'} · {store.mode === 'cloud' ? 'Private cloud research' : 'Research saved in this browser'}</p></div><div className="flex flex-wrap gap-2"><button className={buttonClass} disabled={busy} onClick={refresh}><RefreshCw size={15} className={busy ? 'animate-spin' : ''} />{busy ? 'Refreshing…' : 'Refresh markets'}</button><button className={buttonClass} disabled={!store.ready} onClick={store.exportFile}><Download size={15} />Backup research</button></div></div></div>
    {(error || store.error || notice) && <div role="status" className="space-y-2 rounded-lg border border-warning/30 bg-warning/5 p-4 text-sm">{error && <p>{error}</p>}{store.error && <p>{store.error} <button className="underline" onClick={() => void store.reload()}>Reload research</button></p>}{notice && <p>{notice}</p>}</div>}
    <section aria-label="Market context" className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Market context</h2><a href="https://coinpaprika.com/" target="_blank" rel="noreferrer" className="text-xs text-muted-foreground hover:text-primary">Market data by CoinPaprika ↗</a></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard icon={<Globe2 size={14} />} label="Total market cap" value={currency(g?.marketCap)} sublabel="Provider-wide market estimate" /><StatCard icon={<BarChart3 size={14} />} label="24h volume" value={currency(g?.volume24h)} sublabel="Reported trading volume" /><StatCard icon={<PieChart size={14} />} label="BTC dominance" value={g?.btcDominancePercent == null ? '—' : `${g.btcDominancePercent.toFixed(2)}%`} sublabel="Share of market capitalization" /><StatCard icon={<Bitcoin size={14} />} label="Bitcoin" value={bitcoin?.price == null ? '—' : formatPrice(bitcoin.price)} change={bitcoin?.change24hPercent ?? undefined} sublabel="USD · change over 24h" /><StatCard icon={<Gem size={14} />} label="Ethereum" value={ethereum?.price == null ? '—' : formatPrice(ethereum.price)} change={ethereum?.change24hPercent ?? undefined} sublabel="USD · change over 24h" /></div><div className="grid gap-2 sm:grid-cols-2"><DataStamp result={global} observedAt={g?.sourceUpdatedAt} /><DataStamp result={assets} observedAt={bitcoin?.sourceUpdatedAt} /></div><p className="text-xs text-muted-foreground">Snapshots refresh on opening this page or on request, with a five-minute cache. No automatic trade signal. Each asset keeps its own observation time.</p></section>
    <div className="grid gap-3 sm:grid-cols-3">{[['In your workspace', store.ready ? String(active.length) : '…', 'Active projects you selected'], ['Reviews due', store.ready ? String(due.length) : '…', 'Based on dates you set'], ['Reviewed today', store.ready ? String(reviewedToday.length) : '…', 'Projects with a saved review note']].map(([title, count, sub]) => <Card key={title} className="flex items-center justify-between gap-3 p-4"><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">{sub}</p></div><p className="text-2xl font-semibold text-primary">{count}</p></Card>)}</div>
    <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_300px]">
      <Card className="min-w-0"><CardHeader title="Your market workspace" description="Prices are context. Your research makes the decision." action={<Link className="text-xs text-primary hover:underline" href="/projects">All projects ↗</Link>} /><div className="flex flex-wrap items-center gap-2 border-b border-border/50 px-4 pb-3"><button className={`${buttonClass} ${view === 'projects' ? 'border-primary/30 bg-primary/15 text-foreground' : 'border-transparent bg-secondary/30 text-muted-foreground'}`} onClick={() => { setView('projects'); setLimit(20); }}>My projects</button><button className={`${buttonClass} ${view === 'market' ? 'border-primary/30 bg-primary/15 text-foreground' : 'border-transparent bg-secondary/30 text-muted-foreground'}`} onClick={() => { setView('market'); setLimit(20); }}>Explore market</button><label className="relative min-w-[180px] flex-1"><Search size={15} className="absolute left-3 top-3 text-muted-foreground" /><input className={`${inputClass} pl-9`} value={query} onChange={e => { setQuery(e.target.value); setLimit(20); }} aria-label="Search market workspace" placeholder={view === 'projects' ? 'Search your projects…' : 'Search name or ticker…'} /></label></div>
        {view === 'projects' ? !store.ready ? <p className="p-6 text-sm text-muted-foreground">Loading saved research…</p> : !projectRows.length ? <div className="space-y-3 p-6"><h3 className="text-lg font-semibold">{active.length ? 'No matching projects' : 'Build your research universe'}</h3><p className="max-w-lg text-sm leading-relaxed text-muted-foreground">{active.length ? 'Try a different search.' : 'Start with a few projects you follow. Explore the market to add a mapped asset, or create a research entry for any project.'}</p><div className="flex flex-wrap gap-2"><button className={`${buttonClass} bg-primary text-primary-foreground`} onClick={() => setView('market')}>Explore market <ArrowUpRight size={14} /></button><Link className={buttonClass} href="/projects?add=1">Add a project manually</Link></div></div> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-secondary/20 text-xs text-muted-foreground"><tr>{['Project', 'Price', '24h', 'Next action', 'Review'].map(t => <th key={t} className="px-4 py-3 font-medium">{t}</th>)}</tr></thead><tbody>{projectRows.slice(0, limit).map(p => { const quote = byId.get(p.coinpaprikaId); return <tr className="border-t hover:bg-secondary/20" key={p.id}><td className="px-4 py-3"><Link className="font-semibold hover:text-primary" href={`/projects/${p.id}`}>{p.name} ↗</Link><p className="mt-1 text-xs text-muted-foreground">{p.symbol} · {p.status}</p></td><td className="whitespace-nowrap px-4 py-3 font-mono">{quote?.price == null ? <Link className="text-xs text-muted-foreground hover:text-primary" href={`/projects/${p.id}`}>{p.coinpaprikaId ? 'Not in snapshot' : 'Connect asset'}</Link> : formatPrice(quote.price)}{quote?.sourceUpdatedAt && <p className="mt-1 font-sans text-[10px] text-muted-foreground">{new Date(quote.sourceUpdatedAt).toLocaleString()}</p>}</td><td className="px-4 py-3"><Change value={quote?.change24hPercent} /></td><td className="max-w-[220px] px-4 py-3 text-xs text-muted-foreground"><p className="line-clamp-2">{p.review.nextAction || 'Set your next research action'}</p></td><td className="whitespace-nowrap px-4 py-3 text-xs">{p.review.nextReviewOn ? <span className={p.review.nextReviewOn <= today ? 'text-warning' : 'text-muted-foreground'}>{displayDay(p.review.nextReviewOn)}</span> : 'Not scheduled'}</td></tr>; })}</tbody></table></div>
        : !assets?.ok ? <div className="p-6 text-sm text-muted-foreground">{busy ? 'Loading the market snapshot…' : 'No market snapshot available. Refresh to retry; manual research remains available.'}</div> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-secondary/20 text-xs text-muted-foreground"><tr>{['Asset', 'Price', '24h', '7d', 'Market cap', 'Research'].map(t => <th key={t} className="px-4 py-3 font-medium">{t}</th>)}</tr></thead><tbody>{marketRows.slice(0, limit).map(a => { const saved = store.projects.find(p => p.coinpaprikaId === a.asset.coinpaprikaId); return <tr className="border-t hover:bg-secondary/20" key={a.asset.coinpaprikaId}><td className="px-4 py-3"><p className="font-medium">{a.name}</p><p className="mt-1 text-xs text-muted-foreground">{a.symbol} · {a.rank ? `#${a.rank}` : 'Unranked'}</p></td><td className="whitespace-nowrap px-4 py-3 font-mono">{a.price === null ? '—' : formatPrice(a.price)}<p className="mt-1 font-sans text-[10px] text-muted-foreground">{a.sourceUpdatedAt ? new Date(a.sourceUpdatedAt).toLocaleString() : 'Observation time unavailable'}</p></td><td className="px-4 py-3"><Change value={a.change24hPercent} /></td><td className="px-4 py-3"><Change value={a.change7dPercent} /></td><td className="px-4 py-3 font-mono">{currency(a.marketCap)}</td><td className="px-4 py-3">{saved ? <Link href={`/projects/${saved.id}`} className="text-xs text-primary hover:underline">Open {saved.status === 'Archived' ? 'archived ' : ''}project ↗</Link> : <button className={buttonClass} disabled={store.busy || !store.ready} onClick={() => void add(a)} aria-label={`Watch ${a.name}`}><Plus size={13} />Watch</button>}</td></tr>; })}</tbody></table>{!marketRows.length && <p className="p-5 text-sm text-muted-foreground">No match in this feed. Add the project manually from Projects.</p>}</div>}
        {(view === 'market' ? marketRows.length : projectRows.length) > limit && <div className="border-t p-4"><button className={buttonClass} onClick={() => setLimit(l => l + 20)}>Show 20 more</button></div>}<p className="border-t p-4 text-xs leading-relaxed text-muted-foreground">{view === 'market' ? `${quotes.length} assets returned. Ordered by provider rank, including stablecoins and wrapped assets. Coverage is limited; this is not an altseason index.` : 'Quotes match explicit CoinPaprika asset IDs. No ticker-based matching or inferred holdings.'}{oldest && view === 'market' ? ' Check each row’s observation time before using it.' : ''}</p>
      </Card>
      <div className="space-y-4"><Card><CardHeader title="Research focus" description="Scheduled reviews first, then unfinished research." /><CardBody className="space-y-4">{!store.ready ? <p className="text-sm text-muted-foreground">Loading research…</p> : !queue.length ? <p className="text-sm text-muted-foreground">Add a project to create your first research action.</p> : queue.slice(0, 5).map(({ project: p, due: isDue, coverage }) => <Link className="block rounded-xl border border-border/50 bg-background/40 p-3 hover:border-primary/50" href={`/projects/${p.id}`} key={p.id}><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-sm font-semibold">{p.name}</span>{isDue && <Badge variant="warning">Review due</Badge>}</div><p className="mt-2 line-clamp-2 text-xs text-muted-foreground">{p.review.nextAction || coverage.checks.filter(c => !c.present).slice(0, 2).map(c => `Add ${c.label.toLowerCase()}`).join(' · ') || 'Review your thesis and source evidence'}</p><p className="mt-2 text-[11px] text-muted-foreground">{coverage.filled}/{coverage.total} research areas started · {coverage.toVerify} records to verify</p></Link>)}</CardBody></Card>
      <Card><CardHeader title="Upcoming catalysts" description="Dates you recorded in project research." action={<Link className="text-xs text-primary" href="/calendar">Calendar ↗</Link>} /><CardBody className="space-y-4">{upcoming.length ? upcoming.slice(0, 5).map(({ project, event }) => <Link className="block border-l-2 border-primary/50 pl-3" key={`${project.id}:${event.id}`} href={`/projects/${project.id}`}><p className="text-xs text-primary">{displayDay(event.date)} · {project.symbol || project.name}</p><p className="mt-1 text-sm">{event.title}</p><p className="mt-1 text-xs text-muted-foreground">{event.sourceUrl ? 'Source attached; verify details' : 'Needs a source'}</p></Link>) : <p className="text-sm text-muted-foreground">No upcoming events recorded. Add a dated catalyst in a project’s News &amp; Catalysts section.</p>}</CardBody></Card>
      <Card className="space-y-3 p-5"><h2 className="text-sm font-semibold">Research routine</h2>{['Scan prices and market context', 'Review a project and its evidence', 'Write what changed and your next action'].map((step, i) => <p key={step} className="flex items-start gap-2 text-xs text-muted-foreground"><span className="font-mono text-primary">0{i + 1}</span>{step}</p>)}<Link className="inline-flex items-center gap-2 text-xs text-primary" href="/journal"><CheckCircle2 size={14} />Open your review journal</Link></Card></div>
    </div>
    <Card className="p-5"><h2 className="text-sm font-semibold">Continue your wider research</h2><p className="mt-2 text-sm text-muted-foreground">Open the dashboard for markets, macro observations, headlines and chain activity. Specialist coverage continues to expand.</p><div className="mt-4 flex flex-wrap gap-2">{[['CoinMarketCap', 'https://coinmarketcap.com/'], ['DefiLlama', 'https://defillama.com/'], ['FRED macro data', 'https://fred.stlouisfed.org/'], ['RWA.xyz', 'https://app.rwa.xyz/']].map(([name, url]) => <a key={url} href={url} target="_blank" rel="noreferrer" className={buttonClass}>{name} ↗</a>)}<Link href="/data-sources" className={buttonClass}>Atlas data coverage</Link></div></Card>
  </div>;
}
