'use client';
import { useEffect, useId, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, ArrowUpDown, Filter, Plus, Search } from 'lucide-react';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Card } from '@/components/shared';
import { useProjects } from '@/components/projects/store';
import { useAuth } from '@/components/auth/provider';
import { buttonClass, inputClass } from '@/components/projects/fields';
import { WatchButton } from '@/components/watchlists/add-button';
import { quoteWatchAsset } from '@/lib/watchlists';
import { newProject } from '@/lib/projects';
import { positionSchema } from '@/lib/positions';
import { formatCurrency, formatPrice, formatPercent } from '@/lib/format';
import { monthlyChange } from '@/lib/macro';
import { marketRows, filterMarketRows, marketAssetKey, marketAssetHref, savedMarketProject, portfolioRows, periodChange, marketMetrics, invalidRange, type MarketRange, type MarketView, type MarketSort } from '@/lib/market-dashboard';
import { projectEvents } from '@/lib/research-desk';
import { localDay, displayDay } from '@/lib/research-routine';
import { calendarStarsStorageKey, parseCalendarStars, type CalendarStar } from '@/lib/calendar-stars';
import { scheduledDate, scheduledUpcoming, sortedSchedule } from '@/lib/scheduled-calendar';
import type { ScheduledCalendarEvent } from '@/services/calendar/types';
import type { GlobalMarket, MarketQuote, CmcPerformance } from '@/services/core/types';
import { macroSeries, type MacroId, type MacroSeries, type ChainSnapshot, type RevenueRow, type StablecoinSupply, type Sentiment, type NewsItem, type DexActivity, type SeriesPoint } from '@/services/intelligence/types';
import { marketColumns, defaultMarketColumns, validMarketColumns, unavailableMarketColumns } from '@/lib/market-columns';
import { useFeed, type Feed } from './use-feed';
import { SavedDiscoveryViews } from './saved-views';
import type { DiscoverySettings } from '@/lib/discovery-views';
export const money = (v: number | null | undefined) => v == null ? '—' : `${v < 0 ? '−' : ''}${formatCurrency(Math.abs(v))}`;
export const price = (v: number | null | undefined) => v == null ? '—' : formatPrice(v);
export function Change({ value }: { value: number | null | undefined }) {
  return <span className={`whitespace-nowrap text-xs tabular-nums ${value == null || value === 0 ? 'text-muted-foreground' : value > 0 ? 'text-success' : 'text-destructive'}`}>{value == null ? '—' : formatPercent(value)}</span>;
}
export function Panel({ title, href, children, className = '', label }: { title: string; href?: string; children: React.ReactNode; className?: string; label?: string }) {
  return <Card className={`min-w-0 overflow-hidden ${className}`}><div className="flex items-center justify-between gap-3 px-4 pb-3 pt-4"><h2 className="text-sm font-semibold">{href ? <Link className="group inline-flex items-center gap-2 hover:text-primary" href={href}>{title}<ArrowUpRight size={14} className="text-muted-foreground group-hover:text-primary" /></Link> : title}</h2>{label && <span className="text-[10px] text-muted-foreground">{label}</span>}</div>{children}</Card>;
}
export function FeedNote<T>({ feed, source, url, observed }: { feed: Feed<T>; source: string; url: string; observed?: string | null }) {
  const result = feed.result;
  return <div className="border-t border-border/40 px-4 py-2 text-[10px] text-muted-foreground">
    {feed.error && <p role="status" className="mb-1 text-warning">{feed.error}{feed.data ? ' Showing the previous snapshot.' : ''}</p>}
    {result?.ok && result.warning && <p role="status" className="mb-1 text-warning">{result.warning.message}</p>}
    {result && !result.ok && <p role="status" className="mb-1 text-warning">{result.error.message}</p>}
    <div className="flex flex-wrap items-center justify-between gap-x-2 gap-y-1"><a href={url} target="_blank" rel="noreferrer" className="hover:text-foreground">{source} ↗</a>{!result && <span>{feed.loading ? 'Loading…' : 'Unavailable'}</span>}{result?.ok && <details className="max-w-full"><summary className={`cursor-pointer ${result.meta.cache === 'stale' ? 'text-warning' : ''}`}>{result.meta.cache === 'stale' ? 'Stale fallback' : feed.loading ? 'Refreshing…' : observed ? `As of ${observed.slice(0, 10)}` : `Fetched ${new Date(result.meta.fetchedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`}</summary><p className="mt-1">Retrieved {new Date(result.meta.fetchedAt).toLocaleString()}. Cached until {new Date(result.meta.expiresAt).toLocaleTimeString()}.{observed ? ` Observation: ${observed}.` : ' Observation time not supplied.'}{result.warning ? ` ${result.warning.message}` : ''}</p></details>}</div>
  </div>;
}
function Empty({ children }: { children: React.ReactNode }) { return <div className="px-4 py-6 text-xs leading-relaxed text-muted-foreground">{children}</div>; }
export function HistoryChart({ points, unit = '', compact = false }: { points: SeriesPoint[]; unit?: string; compact?: boolean }) {
  const id = useId().replace(/:/g, '');
  if (points.length < 2) return <div className="py-4 text-xs text-muted-foreground">History unavailable</div>;
  const show = points.slice(-90);
  return <div className={compact ? 'h-[115px] w-full' : 'h-[190px] w-full'}><ResponsiveContainer width="100%" height="100%"><AreaChart data={show} margin={{ top: 10, left: 0, right: 0, bottom: 0 }}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="hsl(var(--primary))" stopOpacity={0.3} /><stop offset="100%" stopColor="hsl(var(--primary))" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="date" hide={compact} tick={{ fontSize: 9, fill: 'hsl(var(--muted-foreground))' }} minTickGap={50} tickLine={false} axisLine={false} tickFormatter={v => String(v).slice(5)} /><YAxis hide domain={['auto', 'auto']} /><Tooltip contentStyle={{ background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: 10, fontSize: 11 }} formatter={(v: number) => [unit === 'USD' ? money(v) : `${v.toLocaleString(undefined, { maximumFractionDigits: 3 })} ${unit}`, 'Value']} labelStyle={{ color: 'hsl(var(--muted-foreground))' }} /><Area type="linear" dataKey="value" stroke="hsl(var(--primary))" strokeWidth={2} fill={`url(#${id})`} isAnimationActive={false} /></AreaChart></ResponsiveContainer></div>;
}
export function MarketTable({ feed, detailed = false, initialLimit = 30, provider = 'coinpaprika', appliedSettings, onApplySettings }: { feed: Feed<MarketQuote[]>; detailed?: boolean; initialLimit?: number; provider?: 'coinmarketcap' | 'coinpaprika'; appliedSettings?: DiscoverySettings | null; onApplySettings?: (settings: DiscoverySettings) => void }) {
  const [view, setView] = useState<MarketView>('leaders'); const [query, setQuery] = useState(''); const [limit, setLimit] = useState(initialLimit); const [notice, setNotice] = useState('');
  const [filtersOpen, setFiltersOpen] = useState(false); const [minCap, setMinCap] = useState(0); const [minVolume, setMinVolume] = useState(0);
  const [sort, setSort] = useState<MarketSort | null>(null); const [descending, setDescending] = useState(false);
  const [ranges, setRanges] = useState<MarketRange[]>([]); const [columnsOpen, setColumnsOpen] = useState(false);
  const [selectedColumns, setSelectedColumns] = useState(defaultMarketColumns); const [columnsReady, setColumnsReady] = useState(false);
  useEffect(() => {
    try { const raw = localStorage.getItem('atlas.discovery.columns.v1'); const saved = raw && validMarketColumns(JSON.parse(raw)); if (saved) setSelectedColumns(saved); } catch { /* Defaults work without storage. */ }
    setColumnsReady(true);
  }, []);
  useEffect(() => { if (columnsReady) try { localStorage.setItem('atlas.discovery.columns.v1', JSON.stringify(selectedColumns)); } catch { /* Keep the session preference. */ } }, [selectedColumns, columnsReady]);
  function applySettings(settings: DiscoverySettings) {
    setView(settings.view); setQuery(settings.query); setMinCap(settings.minCap); setMinVolume(settings.minVolume);
    setSort(settings.sort); setDescending(settings.descending); setRanges(settings.ranges); setSelectedColumns(settings.columns); setLimit(initialLimit); setFiltersOpen(settings.ranges.length > 0 || !!settings.minCap || !!settings.minVolume);
  }
  useEffect(() => { if (appliedSettings) applySettings(appliedSettings);
    // Apply an explicit selection; edits below remain independent until the next selection.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [appliedSettings]);
  const source = (feed.result?.ok ? feed.result.meta.provider : provider) === 'coinmarketcap' ? 'CoinMarketCap' : 'CoinPaprika';
  const needsHistory = detailed && source === 'CoinMarketCap' && (selectedColumns.some(c => ['change4hPercent', 'change12hPercent'].includes(c)) || ranges.some(r => ['change4hPercent', 'change12hPercent'].includes(r.metric)));
  const history = useFeed<CmcPerformance>('/api/data/cmc-performance', feed.result?.ok ? Date.parse(feed.result.meta.fetchedAt) : 0, 6000, needsHistory && !!feed.data);
  const store = useProjects(); const quotes = filterMarketRows(marketRows(marketMetrics(feed.data ?? [], history.data), view, query), minCap, minVolume, sort, descending, ranges);
  const shown = (detailed ? selectedColumns : ['price', 'change24hPercent', 'volume24h']).flatMap(key => marketColumns.filter(c => c.key === key));
  function chooseSort(key: MarketSort) { setDescending(sort === key ? !descending : !['name', 'rank'].includes(key)); setSort(key); }
  function toggleColumn(key: typeof selectedColumns[number]) {
    const next = selectedColumns.includes(key) ? selectedColumns.filter(c => c !== key) : [...selectedColumns, key];
    if (next.length) setSelectedColumns(next);
    if (sort === key && !next.includes(key)) setSort(null);
  }
  function changeRange(index: number, patch: Partial<MarketRange>) { setRanges(rows => rows.map((row, i) => i === index ? { ...row, ...patch } : row)); setLimit(initialLimit); }
  const activeRanges = ranges.filter(r => r.min.trim() || r.max.trim()).length;
  async function watch(q: MarketQuote) {
    if (!q.asset.coinpaprikaId || savedMarketProject(q, store.projects)) return;
    if (await store.save({ ...newProject(q.name, q.symbol), coinpaprikaId: q.asset.coinpaprikaId!, status: 'Watching' })) setNotice(`${q.name} added to your watchlist.`);
  }
  return <Panel title="Crypto markets" href={detailed ? undefined : '/markets'} label="USD · rolling changes"><div className="flex flex-wrap items-center gap-1 px-4 pb-3">{(['leaders', 'gainers', 'losers', 'volume'] as const).map(v => <button key={v} onClick={() => { setView(v); setLimit(initialLimit); setSort(null); }} aria-pressed={view === v} className={`rounded-lg px-2.5 py-1.5 text-[11px] capitalize ${view === v ? 'bg-secondary text-foreground' : 'text-muted-foreground hover:text-foreground'}`}>{v === 'leaders' ? 'Overview' : v === 'volume' ? 'Top volume' : `Top ${v}`}</button>)}</div>
    {detailed && onApplySettings && <SavedDiscoveryViews appliedSettings={appliedSettings} settings={{provider,view,query,minCap,minVolume,sort,descending,ranges,columns:selectedColumns}} apply={onApplySettings} />}
    {detailed && <div className="mx-4 mb-3 flex flex-wrap items-center gap-2"><label className="relative min-w-[150px] flex-1"><Search size={14} className="absolute left-3 top-3 text-muted-foreground" /><input className={`${inputClass} pl-9`} aria-label="Search markets" maxLength={200} placeholder="Search assets" value={query} onChange={e => { setQuery(e.target.value); setLimit(initialLimit); }} /></label><button className={buttonClass} aria-expanded={filtersOpen} onClick={() => setFiltersOpen(v => !v)}><Filter size={13} />Filters{minCap || minVolume || activeRanges ? ` (${Number(!!minCap) + Number(!!minVolume) + activeRanges})` : ''}</button><button className={buttonClass} aria-expanded={columnsOpen} onClick={() => setColumnsOpen(v => !v)}>Columns</button>{sort && <button className={buttonClass} onClick={() => setSort(null)}>Reset sort</button>}</div>}
    {detailed && columnsOpen && <div className="mx-4 mb-3 rounded-lg border border-border p-3"><div className="mb-3 flex items-center justify-between gap-2"><p className="text-xs font-medium">Table columns</p><button className={buttonClass} onClick={() => { setSelectedColumns(defaultMarketColumns); setSort(null); }}>Reset columns</button></div><div className="flex flex-wrap gap-3">{marketColumns.map(c => <label key={c.key} className="flex items-center gap-1.5 text-xs"><input type="checkbox" checked={selectedColumns.includes(c.key)} disabled={selectedColumns.includes(c.key) && selectedColumns.length === 1} onChange={() => toggleColumn(c.key)} />{c.label}</label>)}</div><p className="mt-3 text-[10px] text-muted-foreground">Saved in this browser. 4h/12h values require historical-price access. Name stays visible.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{unavailableMarketColumns.map(c => <label key={c.label} className="flex items-start gap-2 text-[10px] text-muted-foreground"><input type="checkbox" disabled /><span>{c.label} · {c.reason}</span></label>)}</div></div>}
    {detailed && filtersOpen && <div className="mx-4 mb-3 space-y-3 rounded-lg bg-secondary/40 p-3"><div className="flex flex-wrap items-end gap-3">{[{ label: 'Minimum market cap', value: minCap, change: setMinCap }, { label: 'Minimum 24h volume', value: minVolume, change: setMinVolume }].map(f => <label key={f.label} className="text-[10px] text-muted-foreground">{f.label}<select aria-label={f.label} className={`${inputClass} mt-1 block`} value={f.value} onChange={e => { f.change(Number(e.target.value)); setLimit(initialLimit); }}>{[0, 1e6, 1e7, 1e8, 1e9].map(v => <option value={v} key={v}>{v ? money(v) : 'Any'}</option>)}</select></label>)}<button className={buttonClass} disabled={ranges.length >= 8} onClick={() => setRanges(rows => [...rows, { metric: 'change24hPercent', min: '', max: '' }])}>Add metric filter</button><button className={buttonClass} onClick={() => { setMinCap(0); setMinVolume(0); setRanges([]); setLimit(initialLimit); }}>Clear filters</button></div>
      {ranges.map((range, i) => <div key={i} className="flex flex-wrap items-end gap-2"><label className="text-[10px] text-muted-foreground">Metric<select className={`${inputClass} mt-1 block`} aria-label={`Filter ${i + 1} metric`} value={range.metric} onChange={e => changeRange(i, { metric: e.target.value as MarketRange['metric'] })}>{marketColumns.map(c => <option key={c.key} value={c.key}>{c.label}</option>)}</select></label><label className="min-w-0 text-[10px] text-muted-foreground">Minimum<input type="number" step="any" placeholder="Any" className={`${inputClass} mt-1 block w-28`} aria-label={`Filter ${i + 1} minimum`} value={range.min} onChange={e => changeRange(i, { min: e.target.value })} /></label><label className="min-w-0 text-[10px] text-muted-foreground">Maximum<input type="number" step="any" placeholder="Any" className={`${inputClass} mt-1 block w-28`} aria-label={`Filter ${i + 1} maximum`} value={range.max} onChange={e => changeRange(i, { max: e.target.value })} /></label><button className={buttonClass} aria-label={`Remove filter ${i + 1}`} onClick={() => setRanges(rows => rows.filter((_, n) => i !== n))}>Remove</button>{invalidRange(range) && <p role="alert" className="w-full text-xs text-warning">Enter valid bounds with minimum at or below maximum.</p>}</div>)}<p className="text-[10px] text-muted-foreground">Filters combine. Percent values use percentage points (5 means 5%); prices, caps and volume use USD. Missing values are excluded when a bound is set.</p></div>}
    {(notice || store.error) && <p role="status" className="px-4 pb-3 text-xs text-warning">{store.error || notice}</p>}
    <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-y border-border/40 bg-secondary/20 text-[10px] text-muted-foreground"><tr>{[{ label: 'Name', key: 'name' as const }, ...shown].map(h => <th key={h.key} aria-sort={sort === h.key ? descending ? 'descending' : 'ascending' : undefined} className={`px-4 py-2.5 font-normal ${h.key === 'name' ? '' : 'text-right'}`}><button className="inline-flex items-center gap-1 whitespace-nowrap hover:text-foreground" onClick={() => chooseSort(h.key)} aria-label={`Sort by ${h.label}`}>{h.label}<ArrowUpDown size={11} />{sort === h.key && <span>{descending ? '↓' : '↑'}</span>}</button></th>)}{detailed && <th className="px-4 py-2.5 text-right font-normal">Actions</th>}</tr></thead><tbody>{quotes.slice(0, detailed ? limit : 6).map(q => { const saved = savedMarketProject(q, store.projects); return <tr key={marketAssetKey(q)} className="border-b border-border/30 last:border-0 hover:bg-secondary/20"><td className="px-4 py-3"><div className="flex items-center gap-2.5"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-border bg-secondary text-[9px] text-muted-foreground">{q.symbol.slice(0, 3)}</span><div className="min-w-[100px]"><Link className="font-medium hover:text-primary" href={marketAssetHref(q)}>{q.name}</Link><div className="mt-0.5 text-[10px] text-muted-foreground">{q.symbol}</div></div></div></td>{shown.map(c => <td key={c.key} className="whitespace-nowrap px-4 py-3 text-right tabular-nums" title={q.sourceUpdatedAt ? `Quote observed ${q.sourceUpdatedAt}` : 'Quote observation time unavailable'}>{c.kind === 'change' ? <Change value={q[c.key]} /> : c.kind === 'price' ? price(q[c.key]) : c.kind === 'money' ? money(q[c.key]) : q[c.key] ?? '—'}</td>)}{detailed && <td className="px-4 py-3 text-right"><div className="flex items-center justify-end gap-3">{quoteWatchAsset(q) && <WatchButton asset={quoteWatchAsset(q)!} />}{saved ? <Link className="text-primary" href={`/projects/${saved.id}`}>Open</Link> : q.asset.coinmarketcapId !== undefined ? <Link className="text-primary" href={marketAssetHref(q)}>Details</Link> : <button className="inline-flex items-center gap-1 text-primary disabled:opacity-40" disabled={!store.ready || store.busy} onClick={() => void watch(q)}><Plus size={12} />Research</button>}</div></td>}</tr>; })}</tbody></table></div>
    {!quotes.length && <Empty>{feed.loading ? 'Loading markets…' : feed.data ? 'No matching assets.' : 'Market snapshot unavailable.'}</Empty>}
    {detailed && <p className="px-4 pt-3 text-[10px] text-muted-foreground">{Math.min(quotes.length, limit)} of {quotes.length} matching assets · {source} snapshot{source === 'CoinMarketCap' ? ' · top 100 by rank' : ''}</p>}
    {detailed && quotes.length > limit && <button className={`${buttonClass} m-4`} onClick={() => setLimit(v => v + initialLimit)}>Show more</button>}
    {['gainers', 'losers'].includes(view) && <p className="px-4 py-2 text-[10px] text-muted-foreground">24h movers · top {source === 'CoinMarketCap' ? '100' : '200'} by rank · at least $1M reported 24h volume · available feed only</p>}
    {detailed && selectedColumns.some(c => c.endsWith('BtcPercent')) && <p className="px-4 py-2 text-[10px] text-muted-foreground">BTC changes use the token/BTC price ratio over the same window, from this provider’s aligned quotes. They are not USD-return subtraction.</p>}
    {needsHistory && <div className="px-4 py-2 text-[10px] text-muted-foreground"><p>4h/12h use historical CMC prices, with baselines within five minutes of the requested window. Values stay blank when access, coverage or alignment is missing.</p><FeedNote feed={history} source="CMC · 4h/12h history" url="https://coinmarketcap.com/api/" observed={history.data?.anchorAt} /></div>}
    <FeedNote feed={feed} source={source} url={source === 'CoinMarketCap' ? 'https://coinmarketcap.com/' : 'https://coinpaprika.com/'} observed={feed.data?.find(q => q.rank === 1)?.sourceUpdatedAt} />
  </Panel>;
}
const macroGroups: { name: string; ids: MacroId[] }[] = [
  { name: 'Markets & rates', ids: ['DGS10', 'DGS2', 'DFII10', 'FEDFUNDS', 'VIXCLS', 'DTWEXBGS', 'SP500'] },
  { name: 'Inflation & jobs', ids: ['PCEPI', 'PCEPILFE', 'CPIAUCSL', 'UNRATE'] },
  { name: 'Energy & liquidity', ids: ['DCOILWTICO', 'DCOILBRENTEU', 'DHHNGSP', 'M2SL'] },
];
export function MacroPanel({ revision, detailed = false }: { revision: number; detailed?: boolean }) {
  const [group, setGroup] = useState(0);
  const ids: MacroId[] = detailed ? macroGroups[group].ids : ['DGS10', 'DGS2', 'VIXCLS', 'DTWEXBGS', 'SP500', 'DCOILWTICO', 'PCEPILFE', 'M2SL'];
  return <Panel title="Macro markets" href={detailed ? undefined : '/macro'} label="Latest observations">{detailed && <div className="flex flex-wrap gap-1 px-4 pb-2">{macroGroups.map((g, i) => <button key={g.name} onClick={() => setGroup(i)} aria-pressed={group === i} className={`rounded-lg px-3 py-1.5 text-xs ${group === i ? 'bg-secondary' : 'text-muted-foreground'}`}>{g.name}</button>)}</div>}<div className={detailed ? 'grid gap-4 p-4 sm:grid-cols-2 xl:grid-cols-3' : 'px-4'}>{ids.map((id, i) => <MacroMetric key={id} id={id} revision={revision} delay={i * 750} detailed={detailed} />)}</div>{!detailed && <div className="px-4 py-3 text-[10px] text-muted-foreground">Daily / monthly observations · dates vary</div>}</Panel>;
}
function MacroMetric({ id, revision, delay, detailed }: { id: MacroId; revision: number; delay: number; detailed: boolean }) {
  const feed = useFeed<MacroSeries>(`/api/data/intelligence?feed=macro&series=${id}`, revision, delay);
  const meta = macroSeries[id]; const points = feed.data?.points ?? []; const latest = points[points.length - 1]; const previous = points[points.length - 2];
  const inflation = ['PCEPI', 'PCEPILFE', 'CPIAUCSL'].includes(id);
  const mom = monthlyChange(points, 1); const yoy = monthlyChange(points, 12);
  const change = latest && previous && previous.value !== 0 ? (latest.value / previous.value - 1) * 100 : null;
  const value = inflation ? yoy === null ? '—' : `${yoy.toFixed(2)}% YoY` : !latest ? '—' : id === 'M2SL' ? money(latest.value * 1e9) : `${latest.value.toLocaleString(undefined, { maximumFractionDigits: 2, minimumFractionDigits: 2 })}${meta.unit === '%' ? '%' : ''}`;
  return <div className={detailed ? 'rounded-xl border border-border/50 bg-background/30' : 'border-b border-border/40 last:border-0'}><div className={detailed ? 'p-4' : 'py-2.5'}><div className="flex items-center justify-between gap-3"><a href={`https://fred.stlouisfed.org/series/${id}`} target="_blank" rel="noreferrer" className="text-xs text-muted-foreground hover:text-foreground">{meta.name}</a><span className="text-sm font-medium tabular-nums">{value}</span></div><div className="mt-1.5 flex items-center justify-between gap-3 text-[10px] text-muted-foreground"><span>{latest?.date ?? (feed.loading ? 'Loading…' : 'Unavailable')}</span>{inflation ? <span>{mom === null ? 'MoM unavailable' : `${mom >= 0 ? '+' : ''}${mom.toFixed(2)}% MoM`}</span> : meta.unit === '%' && latest && previous ? <span>{id === 'UNRATE' ? `${(latest.value - previous.value).toFixed(2)} pp` : `${((latest.value - previous.value) * 100).toFixed(1)} bps`}</span> : <Change value={change} />}</div>{detailed && <><HistoryChart points={points} unit={meta.unit} /><p className="mt-2 text-[10px] text-muted-foreground">{meta.frequency} · {meta.unit} · {inflation ? 'chart: price-index level; MoM/YoY from exact calendar-month baselines' : 'change vs previous observation'}</p></>}</div>{detailed ? <FeedNote feed={feed} source={meta.source} url={`https://fred.stlouisfed.org/series/${id}`} observed={latest?.date} /> : (feed.error || feed.result?.ok === false || (feed.result?.ok && feed.result.meta.cache === 'stale')) && <p className="pb-2 text-[10px] text-warning">{feed.error ? 'Refresh failed' : feed.result?.ok ? 'Stale fallback' : feed.result?.error.message}</p>}</div>;
}
export function NewsPanel({ revision, detailed = false }: { revision: number; detailed?: boolean }) {
  const coindesk = useFeed<NewsItem[]>('/api/data/intelligence?feed=news&source=coindesk', revision);
  const fed = useFeed<NewsItem[]>('/api/data/intelligence?feed=news&source=federalreserve', revision);
  const cointelegraph = useFeed<NewsItem[]>('/api/data/intelligence?feed=news&source=cointelegraph', revision);
  const ecb = useFeed<NewsItem[]>('/api/data/intelligence?feed=news&source=ecb', revision);
  const feeds = [{ feed: coindesk, name: 'CoinDesk', url: 'https://www.coindesk.com/' }, { feed: cointelegraph, name: 'Cointelegraph', url: 'https://cointelegraph.com/' }, { feed: fed, name: 'Federal Reserve', url: 'https://www.federalreserve.gov/newsevents.htm' }, { feed: ecb, name: 'ECB', url: 'https://www.ecb.europa.eu/home/html/rss.en.html' }];
  const [filter, setFilter] = useState('all'); const [query, setQuery] = useState(''); const [publisher, setPublisher] = useState('all');
  const stories = Array.from(new Map(feeds.flatMap(f => f.feed.data ?? []).map(n => [n.url, n])).values()).filter(n => (filter === 'all' || (filter === 'crypto' ? ['CoinDesk', 'Cointelegraph'].includes(n.source) : ['Federal Reserve', 'ECB'].includes(n.source))) && (publisher === 'all' || publisher === n.source) && (!query || n.title.toLowerCase().includes(query.toLowerCase()))).sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
  return <Panel title="News & policy" href={detailed ? undefined : '/news'}><div className="flex gap-1 px-4 pb-2">{['all', 'crypto', 'policy'].map(v => <button key={v} aria-pressed={v === filter} onClick={() => { setFilter(v); setPublisher('all'); }} className={`rounded-lg px-2.5 py-1.5 text-[11px] capitalize ${filter === v ? 'bg-secondary' : 'text-muted-foreground'}`}>{v}</button>)}</div>{detailed && <div className="flex flex-wrap gap-2 px-4 pb-3"><input className={`${inputClass} min-w-0 flex-1`} value={query} onChange={e => setQuery(e.target.value)} aria-label="Search headlines" placeholder="Search headlines" /><select className={`${inputClass} w-auto`} aria-label="News publisher" value={publisher} onChange={e => setPublisher(e.target.value)}><option value="all">All publishers</option>{feeds.filter(f => filter === 'all' || (filter === 'crypto' ? ['CoinDesk', 'Cointelegraph'].includes(f.name) : ['Federal Reserve', 'ECB'].includes(f.name))).map(f => <option key={f.name}>{f.name}</option>)}</select></div>}<div className="divide-y divide-border/40 px-4">{stories.slice(0, detailed ? 100 : 5).map(n => <a key={n.url} href={n.url} target="_blank" rel="noreferrer" className="group block py-3"><p className="line-clamp-2 text-xs font-medium leading-relaxed group-hover:text-primary">{n.title}</p><p className="mt-1.5 flex flex-wrap gap-x-2 text-[10px] text-muted-foreground"><span>{n.source}</span><time dateTime={n.publishedAt}>{new Date(n.publishedAt).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</time><span>↗</span></p></a>)}</div>{!stories.length && <Empty>{feeds.some(f => f.feed.loading) ? 'Loading headlines…' : 'No headlines available for this view.'}</Empty>}<div className={detailed ? 'grid sm:grid-cols-2' : ''}>{feeds.map(f => <FeedNote key={f.name} feed={f.feed} source={`${f.name} RSS`} url={f.url} />)}</div></Panel>;
}
export function SentimentPanel({ feed, quotes }: { feed: Feed<Sentiment>; quotes: MarketQuote[] }) {
  const points = feed.data?.points ?? []; const last = points[points.length - 1];
  const btc = quotes.find(q => q.asset.coinpaprikaId === 'btc-bitcoin'); const eth = quotes.find(q => q.asset.coinpaprikaId === 'eth-ethereum');
  return <Panel title="Bitcoin sentiment" href="/market-cycle" label="Daily"><div className="px-4 pb-4"><div className="flex items-end justify-between"><span className="text-4xl font-medium tabular-nums">{last?.value ?? '—'}<span className="text-sm text-muted-foreground"> / 100</span></span><span className="rounded-full bg-secondary px-2 py-1 text-xs">{last?.label ?? 'Unavailable'}</span></div><div className="relative my-5 h-1.5 rounded-full bg-gradient-to-r from-destructive via-warning to-success">{last && <span className="absolute -top-1 h-3.5 w-1 rounded-full border border-background bg-foreground" style={{ left: `${Math.min(99, last.value)}%` }} />}</div><div className="flex justify-between text-[10px] text-muted-foreground"><span>Extreme fear</span><span>Extreme greed</span></div><div className="mt-5 flex items-center justify-between border-t border-border/50 pt-3 text-xs"><span className="text-muted-foreground">ETH / BTC</span><span className="tabular-nums">{eth?.price != null && btc?.price ? (eth.price / btc.price).toFixed(5) : '—'}</span></div><p className="mt-1 text-[10px] text-muted-foreground">Quote ratio · no rotation classification</p></div><FeedNote feed={feed} source="Alternative.me · Fear & Greed" url="https://alternative.me/crypto/fear-and-greed-index/" observed={last?.date} /></Panel>;
}
export { DiscoveryPanel as TrendingPanel } from './discovery-panel';

export function ChainPanel({ revision, detailed = false }: { revision: number; detailed?: boolean }) {
  const feed = useFeed<ChainSnapshot[]>('/api/data/intelligence?feed=chains', revision);
  const [query, setQuery] = useState(''); const rows = (feed.data ?? []).filter(c => c.name.toLowerCase().includes(query.toLowerCase()));
  return <Panel title="Chain TVL" href={detailed ? undefined : '/chains'} label="USD">{detailed && <div className="px-4 pb-3"><input className={inputClass} placeholder="Find a chain" aria-label="Find a chain" value={query} onChange={e => setQuery(e.target.value)} /></div>}<div className={`space-y-3 px-4 pb-4 ${detailed ? 'max-h-[640px] overflow-auto' : ''}`}>{rows.slice(0, detailed ? 500 : 5).map((c, i) => <div key={c.name}><div className="mb-1.5 flex justify-between gap-3 text-xs"><span><span className="mr-2 text-[10px] text-muted-foreground">{i + 1}</span>{c.name}</span><span className="tabular-nums">{money(c.tvlUsd)}</span></div><div className="h-1 rounded-full bg-secondary"><div className="h-full rounded-full bg-primary/70" style={{ width: `${c.tvlUsd && feed.data?.[0]?.tvlUsd ? Math.min(100, c.tvlUsd / feed.data[0].tvlUsd * 100) : 0}%` }} /></div></div>)}</div>{!rows.length && <Empty>{feed.loading ? 'Loading chains…' : 'No chain data available.'}</Empty>}<FeedNote feed={feed} source="DefiLlama · TVL" url="https://defillama.com/chains" /></Panel>;
}
export function SupplyPanel({ revision, detailed = false }: { revision: number; detailed?: boolean }) {
  const feed = useFeed<StablecoinSupply>('/api/data/intelligence?feed=stablecoins', revision);
  const points = feed.data?.points ?? []; const last = points[points.length - 1];
  return <Panel title="Stablecoin supply" href={detailed ? undefined : '/chains#stablecoins'}><div className="px-4"><div className="flex items-baseline justify-between gap-2"><p className="text-2xl font-medium tabular-nums">{money(last?.value)}</p><div className="text-right"><Change value={periodChange(points, 7)} /><p className="mt-0.5 text-[10px] text-muted-foreground">7 days</p></div></div><HistoryChart points={points} unit="USD" compact={!detailed} /><p className="pb-3 text-[10px] text-muted-foreground">USD value · {points.slice(-90)[0]?.date ?? '—'} — {last?.date ?? '—'}</p></div><FeedNote feed={feed} source="DefiLlama · stablecoins" url="https://defillama.com/stablecoins" observed={last?.date} /></Panel>;
}
export function RevenuePanel({ revision, detailed = false }: { revision: number; detailed?: boolean }) {
  const feed = useFeed<RevenueRow[]>('/api/data/intelligence?feed=revenue', revision, 1200);
  const [kind, setKind] = useState('all');
  const rows = (feed.data ?? []).filter(r => kind === 'all' || (kind === 'chains' ? r.kind === 'chain' || r.category === 'Chain' : r.kind !== 'chain' && r.category !== 'Chain'));
  return <Panel title="Revenue leaders" href={detailed ? undefined : '/chains#revenue'} label="24h · USD">{detailed && <div className="flex gap-2 px-4 pb-3">{['all', 'chains', 'apps'].map(v => <button key={v} className={`${buttonClass} capitalize ${kind === v ? 'bg-secondary' : ''}`} aria-pressed={kind === v} onClick={() => setKind(v)}>{v}</button>)}</div>}<div className={`divide-y divide-border/40 px-4 ${detailed ? 'max-h-[600px] overflow-auto' : ''}`}>{rows.slice(0, detailed ? 300 : 5).map(r => <a href={r.kind === 'chain' ? `https://defillama.com/chain/${encodeURIComponent(r.name)}` : `https://defillama.com/protocol/${encodeURIComponent(r.slug)}`} target="_blank" rel="noreferrer" className="flex justify-between gap-3 py-3 text-xs hover:text-primary" key={r.slug}><span>{r.name}<span className="mt-1 block text-[10px] text-muted-foreground">{r.category ?? r.kind ?? 'Unclassified'}</span></span><span className="text-right tabular-nums">{money(r.revenue24h)}{detailed && <span className="mt-1 block"><Change value={r.change24h} /></span>}</span></a>)}</div>{!rows.length && <Empty>{feed.loading ? 'Loading revenue…' : 'Revenue data unavailable for this view.'}</Empty>}<p className="px-4 py-2 text-[10px] text-muted-foreground">Reported revenue · not net profit or token-holder income</p><FeedNote feed={feed} source="DefiLlama · daily revenue" url="https://defillama.com/revenue" /></Panel>;
}
export function DexPanel({ revision, detailed = false }: { revision: number; detailed?: boolean }) {
  const feed = useFeed<DexActivity>('/api/data/intelligence?feed=dexActivity', revision, 2400);
  return <Panel title="Venue trading volume" href={detailed ? undefined : '/chains#dex'} label="24h"><div className="px-4 pb-3"><div className="flex items-baseline justify-between"><span className="text-2xl font-medium tabular-nums">{money(feed.data?.volume24h)}</span><Change value={feed.data?.change24h} /></div><p className="mt-1 text-[10px] text-muted-foreground">Includes prediction markets</p><div className="mt-3 divide-y divide-border/40">{feed.data?.venues.slice(0, detailed ? 15 : 3).map(v => <div key={v.name} className="flex justify-between gap-2 py-2.5 text-xs"><span>{v.name}</span><span className="tabular-nums text-muted-foreground">{money(v.volume24h)}</span></div>)}</div></div><FeedNote feed={feed} source="DefiLlama · venue volume" url="https://defillama.com/dexs" /></Panel>;
}
export function PersonalPanel({ quotes, portfolio = false, detailed = false }: { quotes: MarketQuote[]; portfolio?: boolean; detailed?: boolean }) {
  const store = useProjects(); const [editId, setEditId] = useState(''); const [editBase, setEditBase] = useState(''); const [quantity, setQuantity] = useState(''); const [cost, setCost] = useState(''); const [error, setError] = useState(''); const [saved, setSaved] = useState('');
  const positions = portfolioRows(store.projects, quotes); const priced = positions.filter(p => p.value !== null); const total = priced.reduce((sum, p) => sum + p.value!, 0);
  const projects = portfolio ? positions.map(r => r.project) : store.projects.filter(p => ['Watching', 'Buy List'].includes(p.status));
  const quoteMap = new Map(quotes.map(q => [q.asset.coinpaprikaId, q]));
  function select(id: string) { const p = store.projects.find(p => p.id === id); setEditId(id); setEditBase(p?.updatedAt ?? ''); setQuantity(p?.position?.quantity ?? ''); setCost(p?.position?.averageCostUsd ?? ''); setError(''); setSaved(''); }
  async function save(event: React.FormEvent) {
    event.preventDefault(); const p = store.projects.find(p => p.id === editId); if (!p) return;
    if (p.updatedAt !== editBase) { setError('This project changed while you were editing. Copy your entries, then select the project again before saving.'); return; }
    const parsed = positionSchema.safeParse({ quantity: quantity.trim(), averageCostUsd: cost.trim() || null, recordedAt: new Date().toISOString() });
    if (!parsed.success) { setError('Enter a non-negative quantity and optional average cost using a decimal point.'); return; }
    const ok = await store.save({ ...p, position: parsed.data, status: p.status === 'Taking Profit' ? p.status : 'Owned', updatedAt: new Date().toISOString() }, p.updatedAt);
    if (ok) { setSaved(`${p.name} position saved.`); setEditId(''); setError(''); }
  }
  return <Panel title={portfolio ? 'My positions' : 'My watchlist'} href={detailed ? undefined : portfolio ? '/portfolio' : '/watchlists'} label={store.ready ? `${projects.length} ${projects.length === 1 ? 'asset' : 'assets'}` : 'Loading'}>{portfolio && <div className="px-4 pb-3"><div className="flex items-baseline gap-3"><span className="text-2xl font-medium tabular-nums">{priced.length ? money(total) : '—'}</span><span className="text-[10px] text-muted-foreground">{priced.length < positions.length ? `Priced subtotal · ${priced.length}/${positions.length}` : 'Current value'}</span></div></div>}
    {(store.error || error || saved) && <p role="status" className="px-4 pb-3 text-xs text-warning">{store.error || error || saved}</p>}
    {!store.ready ? <Empty>Loading saved projects…</Empty> : !projects.length ? <Empty>{portfolio ? 'Add your position quantities to see portfolio value and performance.' : 'Add assets from Markets to follow them here.'}<Link href={portfolio ? '/portfolio' : '/markets'} className="mt-3 block text-primary">{portfolio ? 'Set up positions' : 'Explore markets'} →</Link></Empty> : <div className="overflow-auto"><table className="w-full text-left text-xs"><thead className="border-y border-border/40 bg-secondary/20 text-[10px] text-muted-foreground"><tr><th className="px-4 py-2 font-normal">Asset</th><th className="px-4 py-2 text-right font-normal">{portfolio ? 'Value' : 'Price'}</th><th className="px-4 py-2 text-right font-normal">24h price</th>{detailed && <><th className="px-4 py-2 text-right font-normal">Unrealized P&amp;L</th><th /></>}</tr></thead><tbody>{projects.slice(0, detailed ? 2000 : 5).map(p => { const q = quoteMap.get(p.coinpaprikaId); const position = positions.find(r => r.project.id === p.id); return <tr key={p.id} className="border-b border-border/30 last:border-0"><td className="px-4 py-3"><Link className="font-medium hover:text-primary" href={`/projects/${p.id}`}>{p.name}</Link><p className="mt-1 text-[10px] text-muted-foreground">{portfolio ? p.position ? `${p.position.quantity} ${p.symbol}` : 'Quantity needed' : p.symbol}</p></td><td className="whitespace-nowrap px-4 py-3 text-right tabular-nums">{portfolio ? money(position?.value) : price(q?.price)}</td><td className="px-4 py-3 text-right"><Change value={q?.change24hPercent} /></td>{detailed && <><td className="px-4 py-3 text-right tabular-nums">{money(position?.unrealized)}</td><td className="px-4 py-3"><button className="text-primary" onClick={() => select(p.id)}>Edit</button></td></>}</tr>; })}</tbody></table></div>}
    {detailed && <form onSubmit={save} className="space-y-3 border-t border-border/50 p-4"><h3 className="text-sm font-medium">Add or update a position</h3><label className="block text-xs text-muted-foreground">Project<select className={`${inputClass} mt-1.5`} value={editId} onChange={e => select(e.target.value)}><option value="">Select a saved project</option>{store.projects.filter(p => p.status !== 'Archived').map(p => <option key={p.id} value={p.id}>{p.name} ({p.symbol})</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-muted-foreground">Quantity<input className={`${inputClass} mt-1.5`} inputMode="decimal" placeholder="0.00" value={quantity} onChange={e => setQuantity(e.target.value)} /></label><label className="text-xs text-muted-foreground">Average cost per token · USD<input className={`${inputClass} mt-1.5`} inputMode="decimal" placeholder="Optional" value={cost} onChange={e => setCost(e.target.value)} /></label></div><div className="flex flex-wrap items-center gap-3"><button disabled={!editId || store.busy || !store.ready} className={`${buttonClass} bg-primary/15`} type="submit">Save position</button><Link className="text-xs text-primary" href="/markets">Add another asset →</Link></div><p className="text-[10px] leading-relaxed text-muted-foreground">Manual quantity snapshot. Set quantity to 0 to close a position. P&amp;L uses your entered average cost; fees, realized gains and transaction accounting are not included. Unknown prices or costs remain blank.</p></form>}
  </Panel>;
}
export function CalendarPanel() {
  const store = useProjects();
  const auth = useAuth();
  const starsKey = calendarStarsStorageKey(auth.session?.user.id ?? 'browser');
  const [savedStars, setSavedStars] = useState<{ key: string; events: CalendarStar[]; error: boolean }>({ key: '', events: [], error: false });
  useEffect(() => {
    if (!auth.ready) return;
    const reload = () => {
      try { setSavedStars({ key: starsKey, events: parseCalendarStars(localStorage.getItem(starsKey)).events, error: false }); }
      catch { setSavedStars({ key: starsKey, events: [], error: true }); }
    };
    reload();
    const sync = (event: StorageEvent) => { if (event.key === starsKey || event.key === null) reload(); };
    window.addEventListener('storage', sync);
    return () => window.removeEventListener('storage', sync);
  }, [auth.ready, starsKey]);
  const bea = useFeed<ScheduledCalendarEvent[]>('/api/data/calendar?source=bea');
  const fomc = useFeed<ScheduledCalendarEvent[]>('/api/data/calendar?source=fomc');
  const bls = useFeed<ScheduledCalendarEvent[]>('/api/data/calendar?source=bls');
  const today = localDay();
  const projectCatalysts = projectEvents(store.projects);
  const officialSchedule = [...(bea.data ?? []), ...(fomc.data ?? []), ...(bls.data ?? [])];
  const officialById = new Map(officialSchedule.map(event => [event.id, event]));
  const projectById = new Map(projectCatalysts.map(item => [`project:${item.project.id}:${item.event.id}`, item]));
  const upcomingStars = savedStars.key === starsKey && !savedStars.error ? savedStars.events.map(star => {
    const live = officialById.get(star.id);
    const project = projectById.get(star.id);
    return { star, title: live?.title ?? project?.event.title ?? star.title,
      dateLabel: live ? scheduledDate(live) : project ? displayDay(project.event.date) : star.dateLabel,
      untilDate: live?.date ?? project?.event.date ?? star.untilDate,
      sortAt: live?.startsAt ?? (live ? `${live.date}T12:00:00Z` : project ? `${project.event.date}T12:00:00Z` : star.sortAt),
      savedDate: !live && !project };
  }).filter(item => item.untilDate >= today).sort((a, b) => a.sortAt.localeCompare(b.sortAt) || a.star.id.localeCompare(b.star.id)).slice(0, 5) : [];
  const saved = projectCatalysts.filter(({ event }) => event.date >= today).slice(0, 2);
  const official = sortedSchedule(officialSchedule).filter(event => scheduledUpcoming(event, Date.now())).slice(0, 3);
  const unavailable = [bea, fomc, bls].every(feed => !feed.loading && !feed.data);
  return <Panel title="Upcoming events" href="/calendar" label="Official + saved">
    <div className="space-y-3 px-4 pb-4"><div className="flex items-center justify-between gap-2"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Your starred events</p><Link href="/calendar?view=starred" className="text-[10px] text-primary">Open watchlist →</Link></div>
      {upcomingStars.map(({ star, title, dateLabel, savedDate }) => <Link key={star.id} href="/calendar?view=starred" className="block border-l-2 border-warning/60 pl-3 hover:text-primary"><p className="text-[10px] text-warning">{dateLabel} · {star.category === 'macro' ? 'Macro' : 'Crypto'}{savedDate ? ' · saved date; verify source' : ''}</p><p className="mt-1 text-xs">{title}</p>{star.note && <p className="mt-1 line-clamp-2 text-[10px] text-muted-foreground">{star.note}</p>}{star.projectId && <p className="mt-1 text-[10px] text-muted-foreground">{store.projects.find(project => project.id === star.projectId)?.name ?? 'Linked project unavailable'}</p>}</Link>)}
      {!upcomingStars.length && <p className="text-xs text-muted-foreground">{savedStars.key === starsKey && savedStars.error ? 'Saved stars could not be loaded. Open the calendar to check your watchlist.' : 'Star calendar dates to keep them in your watchlist.'}</p>}
    </div>
    <div className="space-y-3 border-t border-border/40 px-4 py-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Economic & policy</p>
      {official.map(event => <a key={event.id} href={event.sourceUrl} target="_blank" rel="noreferrer" className="block border-l-2 border-primary/60 pl-3 hover:text-primary"><p className="text-[10px] text-primary">{scheduledDate(event)} · {event.source === 'bea' ? 'BEA' : event.source === 'bls' ? 'BLS via FRED' : 'Fed'}</p><p className="mt-1 text-xs">{event.title}</p></a>)}
      {!official.length && <p className="text-xs text-muted-foreground">{bea.loading || fomc.loading || bls.loading ? 'Loading official dates…' : unavailable ? 'Official schedules unavailable.' : 'No upcoming dates in the available schedules.'}</p>}
    </div>
    <div className="space-y-3 border-t border-border/40 px-4 py-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Your project catalysts</p>{saved.map(({ project, event }) => <Link key={`${project.id}:${event.id}`} href={`/projects/${project.id}`} className="block border-l-2 border-primary/40 pl-3"><p className="text-[10px] text-primary">{displayDay(event.date)}</p><p className="mt-1 text-xs">{event.title}</p><p className="mt-1 text-[10px] text-muted-foreground">{project.symbol || project.name}</p></Link>)}{!saved.length && <p className="text-xs text-muted-foreground">{store.ready ? 'No upcoming project events saved.' : 'Loading saved events…'}</p>}</div>
    <div className="border-t border-border/40 px-4 py-3 text-[10px] text-muted-foreground">BLS dates via FRED; <a href="https://www.bls.gov/schedule/" target="_blank" rel="noreferrer" className="text-primary">verify with BLS ↗</a>{bls.result?.ok === false ? ' · Feed unavailable' : bls.result?.ok && bls.result.warning ? ' · Dates may be incomplete' : ''}</div>
  </Panel>;
}
