'use client';
import { useEffect, useState } from 'react';
import { buttonClass, inputClass } from '@/components/projects/fields';
import { appendDiscoveryView, discoveryPreset, discoveryPresets, discoveryViewsKey, parseDiscoveryViews, type DiscoverySettings, type DiscoveryViewsFile } from '@/lib/discovery-views';
export function SavedDiscoveryViews({settings,appliedSettings,apply}:{settings:DiscoverySettings;appliedSettings?:DiscoverySettings|null;apply:(settings:DiscoverySettings)=>void}) {
  const [file,setFile]=useState<DiscoveryViewsFile>({version:1,views:[]}); const [raw,setRaw]=useState<string|null>(null); const [ready,setReady]=useState(false);
  const [name,setName]=useState(''); const [adding,setAdding]=useState(false); const [choice,setChoice]=useState(''); const [notice,setNotice]=useState('');
  function reload() { try { const value=localStorage.getItem(discoveryViewsKey); setFile(parseDiscoveryViews(value)); setRaw(value); setReady(true); setNotice(''); } catch { setReady(false); setNotice('Saved views could not be loaded. Existing data has been kept.'); } }
  useEffect(()=> { reload(); const sync=(e:StorageEvent)=> { if(e.key===discoveryViewsKey || e.key===null) reload(); }; window.addEventListener('storage',sync); return ()=>window.removeEventListener('storage',sync); },[]);
  useEffect(()=> { if (appliedSettings) { const saved=file.views.find(v=>JSON.stringify(v.settings)===JSON.stringify(appliedSettings)); const preset=discoveryPresets.find(p=>JSON.stringify(discoveryPreset(p.id,appliedSettings.provider))===JSON.stringify(appliedSettings)); setChoice(saved?.id ?? preset?.id ?? ''); } },[appliedSettings,file]);
  function remove() { try { if(localStorage.getItem(discoveryViewsKey)!==raw) throw Error('Saved views changed. Reload views before removing one.'); const next={...file,views:file.views.filter(v=>v.id!==choice)}; const value=JSON.stringify(next); localStorage.setItem(discoveryViewsKey,value); setRaw(value); setFile(next); setChoice(''); setNotice('View removed. Current table settings are kept.'); } catch { setNotice('Could not remove this view. Reload views and retry.'); } }
  function choose(id:string) { setChoice(id); const config=discoveryPreset(id,settings.provider) ?? file.views.find(v=>v.id===id)?.settings; if(config) apply(config); }
  function save(e:React.FormEvent) { e.preventDefault(); try { const id=crypto.randomUUID(); const next=appendDiscoveryView(localStorage.getItem(discoveryViewsKey),raw,{id,name,settings}); const value=JSON.stringify(next); localStorage.setItem(discoveryViewsKey,value); setRaw(value); setFile(next); setChoice(id); setName(''); setAdding(false); setNotice('View saved in this browser.'); } catch(e) { setNotice(e instanceof Error && !('issues' in e) ? e.message : 'Use a unique name, valid filters and at most 20 saved views. Your current settings are unchanged.'); } }
  return <div className="mx-4 mb-3 space-y-2"><div className="flex flex-wrap items-center gap-2"><select className={`${inputClass} w-auto max-w-full`} aria-label="Discovery view" value={choice} onChange={e=>choose(e.target.value)}><option value="">Choose a view…</option><optgroup label="Quick views">{discoveryPresets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</optgroup>{file.views.length>0 && <optgroup label="Saved in this browser">{file.views.map(v=><option key={v.id} value={v.id}>{v.name} · {v.settings.provider==='coinmarketcap'?'CMC':'CoinPaprika'}</option>)}</optgroup>}</select><button className={buttonClass} disabled={!ready} onClick={()=>setAdding(v=>!v)}>Save current view</button>{file.views.some(v=>v.id===choice) && <button className={buttonClass} disabled={!ready} onClick={remove}>Remove saved view</button>}<button className={buttonClass} onClick={()=>{setChoice('');apply({...settings,view:'leaders',query:'',minCap:0,minVolume:0,sort:null,descending:false,ranges:[]});}}>Clear view</button></div>
    {choice && <p className="text-[10px] text-muted-foreground">{discoveryPresets.find(p=>p.id===choice) ? `Starting filters: ${discoveryPresets.find(p=>p.id===choice)!.description}` : 'Saved starting settings; use the controls below to adjust them.'}</p>}
    {adding && <form onSubmit={save} className="flex flex-wrap gap-2"><input aria-label="Saved view name" placeholder="Name this view" required maxLength={60} className={`${inputClass} min-w-0 flex-1`} value={name} onChange={e=>setName(e.target.value)} /><button className={buttonClass} disabled={!ready || !name.trim()}>Save view</button><button className={buttonClass} type="button" onClick={()=>setAdding(false)}>Cancel</button></form>}
    {notice && <p role="status" className="text-xs text-muted-foreground">{notice} <button className="text-primary" onClick={reload}>Reload views</button></p>}
  </div>;
}
