'use client';
import { useEffect, useState } from 'react';
import { Badge, Card, PageHeader } from '@/components/shared';
import { dataSourceMap, implementedCapabilities } from '@/services/catalog';
import type { ProviderStatus } from '@/services/core/types';
import { buttonClass } from '@/components/projects/fields';
const stateNames = { idle: 'Ready · not yet used', healthy: 'Last request succeeded', degraded: 'Last request failed', disabled: 'Disabled', missing_key: 'Needs API key' };
export default function DataSourcesPage() {
  const [providers, setProviders] = useState<ProviderStatus[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function refresh() { setBusy(true); setError(''); try { const r = await fetch('/api/data/status', { signal: AbortSignal.timeout(10000) }); if (!r.ok) throw Error(); const data = await r.json(); setProviders(data.providers); } catch { setError('Could not read provider status. Please try again.'); } finally { setBusy(false); } }
  useEffect(() => { void refresh(); }, []);
  return <div className="space-y-6"><PageHeader title="Data Sources" description="Know what is connected, what is missing, and where your research comes from."><button onClick={refresh} disabled={busy} className={buttonClass}>{busy ? 'Checking…' : 'Refresh status'}</button></PageHeader>
    {error && <p role="alert" className="text-sm text-warning">{error}</p>}
    <div className="grid gap-4 lg:grid-cols-3">{providers.map(p => <Card key={p.id} className="space-y-3 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold capitalize">{p.id}</h2><Badge variant={p.state === 'healthy' ? 'success' : p.state === 'missing_key' || p.state === 'degraded' ? 'warning' : 'outline'}>{stateNames[p.state]}</Badge></div><p className="text-xs text-muted-foreground">Last success: {p.lastSuccessAt ? new Date(p.lastSuccessAt).toLocaleString() : 'No request observed'}</p>{p.lastError && <p className="text-sm text-warning">{p.lastError.message}</p>}<p className="text-xs text-muted-foreground">{p.requests} requests · {p.failures} failures in this running instance</p>{p.id === 'coingecko' && p.state === 'missing_key' && <p className="text-sm">Add your CoinGecko Demo key to the server configuration, then restart Atlas. Keys are never entered into this page.</p>}</Card>)}</div>
    <p className="text-xs text-muted-foreground">Status describes observed requests in this running instance. Refreshing status does not test upstream providers. Research entries are stored separately in your selected account or browser workspace.</p>
    <Card className="p-5"><h2 className="font-semibold">First working connections</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">The dashboard combines CMC top-100 discovery, token reference details, global metrics and sentiment/altseason, CoinPaprika wider discovery/personal quotes, FRED inflation/jobs/yield/energy observations, CoinDesk/Cointelegraph and Federal Reserve/ECB headlines, CoinGecko trending searches and DefiLlama chain TVL, supply, venue activity and revenue. Each section shows its source and opens a detail view. CoinGecko exchange listings still need a Demo key; trending searches use the separately checked public endpoint. X, detailed derivatives, global policy rates, RWA details and automated economic events remain planned.</p></Card>
    <Card><div className="border-b p-5"><h2 className="font-semibold">Complete source map</h2><p className="mt-1 text-sm text-muted-foreground">Candidate sources are a roadmap. Planned sources are not connected or guaranteed to be available on a free plan.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-secondary/30 text-muted-foreground"><tr><th className="p-4 font-medium">Domain</th><th className="p-4 font-medium">Candidate sources</th><th className="p-4 font-medium">Available now</th></tr></thead><tbody>{Object.entries(dataSourceMap).map(([domain, sources]) => <tr className="border-t" key={domain}><td className="p-4 font-medium">{domain.replace(/([A-Z])/g, ' $1')}</td><td className="max-w-lg p-4 text-muted-foreground">{sources.join(' · ')}</td><td className="p-4 text-xs">{implementedCapabilities[domain as keyof typeof implementedCapabilities] ?? 'Planned'}</td></tr>)}</tbody></table></div></Card>
  </div>;
}
