/** Planning catalog, not a claim that a provider or paid endpoint is connected. */
export const dataSourceMap = {
  market: ['CoinMarketCap', 'CoinGecko', 'CoinStats', 'CoinPaprika'],
  global: ['CoinMarketCap', 'CoinGecko', 'CoinPaprika'],
  sentiment: ['Alternative.me', 'CoinMarketCap', 'cryptocurrency.cv', 'LunarCrush', 'Santiment'],
  candles: ['Mobula', 'Binance', 'CoinGecko'],
  charts: ['TradingView'],
  technical: ['altFINS', 'Atlas'],
  dex: ['DexScreener', 'Mobula', 'CoinMarketCap DEX'],
  projects: ['RootData', 'CoinMarketCap', 'CoinGecko', 'CoinPaprika', 'TokenInsight', 'Messari'],
  ratings: ['TokenInsight', 'RootData', 'Messari'],
  tokenomics: ['Mobula', 'CoinMarketCap', 'CoinGecko', 'manual'],
  sales: ['manual CryptoRank/ICO Drops', 'RootData', 'Mobula', 'Dropstab'],
  funding: ['RootData', 'manual CryptoRank', 'Dropstab', 'Messari'],
  investors: ['RootData', 'TokenInsight', 'CryptoRank', 'Dropstab'],
  unlocks: ['Mobula', 'manual', 'Apify', 'Dropstab', 'CryptoRank', 'Messari'],
  defi: ['DefiLlama', 'Dune', 'Token Terminal'],
  stablecoins: ['DefiLlama', 'Dune', 'Glassnode'],
  flows: ['DefiLlama', 'Dune', 'Mobula', 'Nansen'],
  onchain: ['Mobula', 'Dune', 'CoinMarketCap DEX', 'Glassnode', 'Nansen', 'Arkham'],
  rpc: ['Alchemy', 'native RPC'],
  wallets: ['Mobula', 'Dune', 'Arkham', 'Nansen'],
  derivatives: ['Binance', 'Mobula', 'exchange APIs', 'CoinGlass'],
  news: ['CoinDesk RSS', 'Cointelegraph RSS', 'Federal Reserve RSS', 'ECB RSS', 'cryptocurrency.cv', 'RSS', 'TokenInsight', 'CoinGecko News', 'Messari'],
  social: ['Reddit', 'Atlas news-volume', 'CoinGecko', 'LunarCrush', 'Santiment', 'X'],
  search: ['CoinGecko trending searches', 'Google Trends (access conditional)', 'manual'],
  developer: ['GitHub'],
  calendar: ['RootData', 'CoinMarketCal', 'manual', 'news', 'Dropstab', 'CryptoRank'],
  macroCalendar: ['FRED', 'official calendars', 'manual', 'Trading Economics'],
  macro: ['FRED', 'BEA', 'World Bank', 'Trading Economics', 'CME (access to verify)', 'Kalshi (access to verify)'],
  globalMarkets: ['Twelve Data', 'Alpha Vantage', 'TradingView charts'],
  geopolitics: ['GDELT', 'Stabilarity'],
  regulation: ['GDELT', 'news', 'official sources', 'manual', 'Messari'],
  rwa: ['RWA.xyz (access to verify)', 'Official issuers', 'CoinMarketCap RWA', 'RootData'],
  economics: ['DefiLlama', 'Token Terminal', 'Official disclosures'],
  organizations: ['Official counterparties', 'Universities/institutes', 'RootData'],
  security: ['Mobula', 'CoinMarketCap DEX', 'CoinStats'],
  portfolio: ['CoinStats', 'Mobula', 'Atlas manual holdings', 'Nansen'],
  listingEvents: ['calendar', 'news', 'exchange APIs', 'manual', 'Dropstab', 'CryptoRank'],
  exchanges: ['CoinGecko', 'CCXT', 'DexScreener'],
  liquidity: ['CCXT order books', 'DexScreener pools', 'Atlas calculations'],
  watchlists: ['Atlas database'], research: ['Atlas database'], alerts: ['Atlas'],
  cycle: ['Atlas', 'market data', 'Glassnode'],
  narratives: ['Atlas', 'DexScreener', 'news tagging', 'LunarCrush', 'Messari'],
  setups: ['Atlas', 'altFINS'], ai: ['future LLM API'],
} as const;
export type ServiceDomain = keyof typeof dataSourceMap;
export const implementedCapabilities = {
  market: 'CMC top-100/reference details and recent additions; CoinPaprika wider discovery/personal quotes and five-day additions; CoinGecko quotes (key required)', global: 'CMC global metrics with CoinPaprika fallback; CoinGecko available separately',
  projects: 'CMC on-demand reference metadata; CoinPaprika sourced profile snapshots', research: 'Private projects, reviews and research coverage',
  calendar: 'User-recorded project catalysts', watchlists: 'Browser-local named lists, exact provider assets, notes/status, paste preview and separate backups; existing research watchlist',
  exchanges: 'CoinGecko paginated tickers', dex: 'DexScreener token pools',
  defi: 'DefiLlama chain/protocol TVL and covered venue volume', liquidity: 'returned-pool liquidity summary',
  sentiment: 'CMC Crypto Fear & Greed and Altcoin Season; separate Alternative.me Bitcoin index',
  stablecoins: 'DefiLlama USD-valued total supply and history',
  economics: 'DefiLlama daily chain/protocol revenue rankings',
  macro: 'FRED: nominal/real US yields, fed funds, US M2, PCE/core PCE, CPI and unemployment',
  globalMarkets: 'FRED: VIX, broad US dollar, S&P 500, WTI/Brent and Henry Hub spot gas',
  news: 'CoinDesk/Cointelegraph headlines and Federal Reserve/ECB RSS',
  search: 'CoinGecko most-searched coins; not X/social trends',
  portfolio: 'Manual quantity/average-cost snapshots, priced subtotal and unrealized P&L',
} as const;
