/** Planning catalog, not a claim that a provider or paid endpoint is connected. */
export const dataSourceMap = {
  market: ['CoinMarketCap', 'CoinGecko', 'CoinStats', 'CoinPaprika'],
  global: ['CoinMarketCap', 'CoinGecko'],
  sentiment: ['CoinMarketCap', 'cryptocurrency.cv', 'LunarCrush', 'Santiment'],
  candles: ['Mobula', 'Binance', 'CoinGecko'],
  charts: ['TradingView'],
  technical: ['altFINS', 'Atlas'],
  dex: ['DexScreener', 'Mobula', 'CoinMarketCap DEX'],
  projects: ['RootData', 'CoinMarketCap', 'CoinGecko', 'TokenInsight', 'Messari'],
  ratings: ['TokenInsight', 'RootData', 'Messari'],
  tokenomics: ['Mobula', 'CoinMarketCap', 'CoinGecko', 'manual'],
  sales: ['manual CryptoRank/ICO Drops', 'RootData', 'Mobula', 'Dropstab'],
  funding: ['RootData', 'manual CryptoRank', 'Dropstab', 'Messari'],
  investors: ['RootData', 'TokenInsight', 'CryptoRank', 'Dropstab'],
  unlocks: ['Mobula', 'manual', 'Apify', 'Dropstab', 'CryptoRank', 'Messari'],
  defi: ['DefiLlama', 'Dune', 'Token Terminal'],
  stablecoins: ['DefiLlama', 'Dune', 'Glassnode'],
  flows: ['DefiLlama', 'Dune', 'Mobula', 'Nansen'],
  onchain: ['Mobula', 'Dune', 'CoinMarketCap DEX', 'Glassnode', 'Nansen', 'Arkham'],
  rpc: ['Alchemy', 'native RPC'],
  wallets: ['Mobula', 'Dune', 'Arkham', 'Nansen'],
  derivatives: ['Binance', 'Mobula', 'exchange APIs', 'CoinGlass'],
  news: ['cryptocurrency.cv', 'RSS', 'TokenInsight', 'CoinGecko News', 'Messari'],
  social: ['Reddit', 'Atlas news-volume', 'CoinGecko', 'LunarCrush', 'Santiment', 'X'],
  search: ['Google Trends (access conditional)', 'manual'],
  developer: ['GitHub'],
  calendar: ['RootData', 'CoinMarketCal', 'manual', 'news', 'Dropstab', 'CryptoRank'],
  macroCalendar: ['FRED', 'official calendars', 'manual', 'Trading Economics'],
  macro: ['FRED', 'World Bank', 'Trading Economics'],
  globalMarkets: ['Twelve Data', 'Alpha Vantage', 'TradingView charts'],
  geopolitics: ['GDELT', 'Stabilarity'],
  regulation: ['GDELT', 'news', 'official sources', 'manual', 'Messari'],
  rwa: ['CoinMarketCap RWA', 'RootData'],
  security: ['Mobula', 'CoinMarketCap DEX', 'CoinStats'],
  portfolio: ['CoinStats', 'Mobula', 'Atlas manual holdings', 'Nansen'],
  listingEvents: ['calendar', 'news', 'exchange APIs', 'manual', 'Dropstab', 'CryptoRank'],
  exchanges: ['CoinGecko', 'CCXT', 'DexScreener'],
  liquidity: ['CCXT order books', 'DexScreener pools', 'Atlas calculations'],
  watchlists: ['Atlas database'], research: ['Atlas database'], alerts: ['Atlas'],
  cycle: ['Atlas', 'market data', 'Glassnode'],
  narratives: ['Atlas', 'DexScreener', 'news tagging', 'LunarCrush', 'Messari'],
  setups: ['Atlas', 'altFINS'], ai: ['future LLM API'],
} as const;
export type ServiceDomain = keyof typeof dataSourceMap;
export const implementedCapabilities = {
  market: 'CoinGecko quotes', global: 'CoinGecko global metrics',
  exchanges: 'CoinGecko paginated tickers', dex: 'DexScreener token pools',
  defi: 'DefiLlama protocol TVL', liquidity: 'returned-pool liquidity summary',
} as const;
