import type {
  AssetPrice,
  MarketStatus,
  NarrativeItem,
  ProjectResearchItem,
  WatchlistItem,
  ConvictionItem,
  JournalEntry,
  NewsItem,
  CalendarEvent,
  MarketCyclePhase,
  MacroIndicator,
  AIResearchSession,
} from './types';

function generateSparkline(base: number, volatility: number, points: number, trend: number = 0): number[] {
  const result: number[] = [];
  let current = base;
  for (let i = 0; i < points; i++) {
    const noise = (Math.random() - 0.5) * volatility;
    current = current * (1 + noise + trend / points);
    result.push(current);
  }
  return result;
}

export const mockPrices: AssetPrice[] = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    price: 67234.5,
    change24h: 2.34,
    change7d: 5.12,
    volume24h: 38_400_000_000,
    marketCap: 1_325_000_000_000,
    sparkline: generateSparkline(67000, 0.015, 30, 0.05),
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    price: 3412.8,
    change24h: 1.87,
    change7d: 3.45,
    volume24h: 18_200_000_000,
    marketCap: 410_000_000_000,
    sparkline: generateSparkline(3400, 0.02, 30, 0.03),
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    price: 178.42,
    change24h: 4.21,
    change7d: 8.34,
    volume24h: 4_100_000_000,
    marketCap: 82_000_000_000,
    sparkline: generateSparkline(175, 0.03, 30, 0.08),
  },
  {
    symbol: 'AVAX',
    name: 'Avalanche',
    price: 38.91,
    change24h: -1.23,
    change7d: 2.1,
    volume24h: 580_000_000,
    marketCap: 14_200_000_000,
    sparkline: generateSparkline(39, 0.025, 30, -0.01),
  },
];

export const mockMarketStatus: MarketStatus = {
  label: 'Risk-On',
  sentiment: 'risk-on',
  fearGreedIndex: 72,
  fearGreedLabel: 'Greed',
};

export const mockNarratives: NarrativeItem[] = [
  {
    id: 'n1',
    title: 'Restaking & EigenLayer Ecosystem',
    description: 'Restaking primitives are unlocking new economic security models. AVS ecosystem expanding rapidly with 15+ active networks.',
    momentum: 94,
    trend: 'up',
    mentions24h: 12450,
    changeMentions: 23.5,
    topProjects: ['EigenLayer', 'Renzo', 'Ether.fi', 'Kelp DAO'],
    category: 'DeFi',
    age: '4 months',
  },
  {
    id: 'n2',
    title: 'Modular Blockchains & Celestia',
    description: 'Modular thesis gaining traction as data availability layers separate from execution. Celestia DA growing.',
    momentum: 81,
    trend: 'up',
    mentions24h: 8230,
    changeMentions: 12.1,
    topProjects: ['Celestia', 'Avail', 'EigenDA', 'Near DA'],
    category: 'Infrastructure',
    age: '6 months',
  },
  {
    id: 'n3',
    title: 'Bitcoin L2s & BitVM',
    description: 'Bitcoin Layer 2 scaling solutions gaining momentum. BitVM enabling smart contracts on Bitcoin.',
    momentum: 76,
    trend: 'up',
    mentions24h: 6890,
    changeMentions: 18.7,
    topProjects: ['Stacks', 'RSK', 'BitVM', 'B² Network'],
    category: 'Infrastructure',
    age: '3 months',
  },
  {
    id: 'n4',
    title: 'AI Agents & DeFi Integration',
    description: 'AI-driven DeFi protocols and autonomous agents emerging as a key narrative. Trading bots, yield optimizers.',
    momentum: 88,
    trend: 'up',
    mentions24h: 15600,
    changeMentions: 34.2,
    topProjects: ['Bittensor', 'Fetch.ai', 'Ocean Protocol', 'Autonolas'],
    category: 'AI',
    age: '2 months',
  },
  {
    id: 'n5',
    title: 'Real World Assets (RWA)',
    description: 'Tokenized treasuries and real-world assets gaining institutional interest. Blackrock BUIDL fund milestone.',
    momentum: 72,
    trend: 'up',
    mentions24h: 5400,
    changeMentions: 8.3,
    topProjects: ['Ondo', 'MakerDAO', 'Centrifuge', 'Maple'],
    category: 'DeFi',
    age: '8 months',
  },
  {
    id: 'n6',
    title: 'MEV & Intent-Based Architecture',
    description: 'Intent-based trading replacing traditional AMM flows. MEV infrastructure evolving with solver competition.',
    momentum: 64,
    trend: 'flat',
    mentions24h: 3200,
    changeMentions: -2.1,
    topProjects: ['UniswapX', 'CoW Protocol', '1inch Fusion', 'Flashbots'],
    category: 'DeFi',
    age: '5 months',
  },
];

export const mockProjects: ProjectResearchItem[] = [
  {
    id: 'p1',
    name: 'EigenLayer',
    symbol: 'EIGEN',
    sector: 'Restaking Infrastructure',
    rank: 22,
    marketCap: 5_200_000_000,
    price: 3.42,
    change24h: 3.21,
    conviction: 'high',
    status: 'conviction',
    tags: ['Restaking', 'Infrastructure', 'Ethereum'],
    lastUpdated: '2 hours ago',
    summary: 'Pioneer of restaking, enabling ETH stakers to extend security to AVS networks. TVL dominance with $15B+ restaked.',
  },
  {
    id: 'p2',
    name: 'Celestia',
    symbol: 'TIA',
    sector: 'Data Availability',
    rank: 38,
    marketCap: 1_800_000_000,
    price: 11.23,
    change24h: 5.67,
    conviction: 'high',
    status: 'conviction',
    tags: ['Modular', 'DA', 'Infrastructure'],
    lastUpdated: '4 hours ago',
    summary: 'Leading modular DA layer. First purpose-built blockchain for data availability sampling and light client verification.',
  },
  {
    id: 'p3',
    name: 'Ondo Finance',
    symbol: 'ONDO',
    sector: 'RWA / Tokenization',
    rank: 45,
    marketCap: 1_100_000_000,
    price: 1.56,
    change24h: -1.34,
    conviction: 'medium',
    status: 'watching',
    tags: ['RWA', 'Tokenization', 'Institutional'],
    lastUpdated: '1 day ago',
    summary: 'Tokenized treasuries and institutional-grade RWA products. USDY and OUSG products seeing strong institutional demand.',
  },
  {
    id: 'p4',
    name: 'Bittensor',
    symbol: 'TAO',
    sector: 'AI / Decentralized Compute',
    rank: 28,
    marketCap: 3_400_000_000,
    price: 487.2,
    change24h: 7.89,
    conviction: 'high',
    status: 'conviction',
    tags: ['AI', 'Compute', 'Machine Learning'],
    lastUpdated: '6 hours ago',
    summary: 'Decentralized machine learning network. Subnet architecture incentivizes AI model training and intelligence production.',
  },
  {
    id: 'p5',
    name: 'Jupiter',
    symbol: 'JUP',
    sector: 'DEX / Solana Ecosystem',
    rank: 31,
    marketCap: 2_600_000_000,
    price: 0.68,
    change24h: 2.1,
    conviction: 'medium',
    status: 'researching',
    tags: ['DEX', 'Solana', 'Aggregator'],
    lastUpdated: '12 hours ago',
    summary: 'Leading Solana DEX aggregator. Expanding into perps and launchpad. Strong revenue and token buyback mechanics.',
  },
  {
    id: 'p6',
    name: 'Hyperliquid',
    symbol: 'HYPE',
    sector: 'Perp DEX',
    rank: 52,
    marketCap: 800_000_000,
    price: 26.7,
    change24h: -2.45,
    conviction: 'medium',
    status: 'watching',
    tags: ['Perps', 'DEX', 'L1'],
    lastUpdated: '1 day ago',
    summary: 'High-performance perp DEX with own L1. Sub-second finality, zero gas fees for trading. Growing market share.',
  },
  {
    id: 'p7',
    name: 'Pendle',
    symbol: 'PENDLE',
    sector: 'Yield Trading',
    rank: 48,
    marketCap: 950_000_000,
    price: 5.34,
    change24h: 1.12,
    conviction: 'high',
    status: 'conviction',
    tags: ['Yield', 'DeFi', 'Ethereum'],
    lastUpdated: '3 hours ago',
    summary: 'Yield tokenization protocol. PT/YT split enables fixed yield trading and yield leverage. TVL surge with restaking.',
  },
  {
    id: 'p8',
    name: 'Monad',
    symbol: 'MON',
    sector: 'L1 / EVM',
    rank: 0,
    marketCap: 0,
    price: 0,
    change24h: 0,
    conviction: 'low',
    status: 'researching',
    tags: ['L1', 'EVM', 'Parallel'],
    lastUpdated: '5 days ago',
    summary: 'High-performance EVM-compatible L1 with 10K TPS target. Still in testnet. Backed by Paradigm and Jump.',
  },
];

export const mockWatchlist: WatchlistItem[] = [
  {
    id: 'w1',
    name: 'Bitcoin',
    symbol: 'BTC',
    price: 67234.5,
    change24h: 2.34,
    change7d: 5.12,
    marketCap: 1_325_000_000_000,
    volume24h: 38_400_000_000,
    sparkline: generateSparkline(67000, 0.015, 30, 0.05),
    alerts: 2,
  },
  {
    id: 'w2',
    name: 'Ethereum',
    symbol: 'ETH',
    price: 3412.8,
    change24h: 1.87,
    change7d: 3.45,
    marketCap: 410_000_000_000,
    volume24h: 18_200_000_000,
    sparkline: generateSparkline(3400, 0.02, 30, 0.03),
    alerts: 1,
  },
  {
    id: 'w3',
    name: 'Solana',
    symbol: 'SOL',
    price: 178.42,
    change24h: 4.21,
    change7d: 8.34,
    marketCap: 82_000_000_000,
    volume24h: 4_100_000_000,
    sparkline: generateSparkline(175, 0.03, 30, 0.08),
    alerts: 3,
  },
  {
    id: 'w4',
    name: 'Pendle',
    symbol: 'PENDLE',
    price: 5.34,
    change24h: 1.12,
    change7d: -3.2,
    marketCap: 950_000_000,
    volume24h: 180_000_000,
    sparkline: generateSparkline(5.3, 0.035, 30, -0.02),
    alerts: 0,
  },
  {
    id: 'w5',
    name: 'Celestia',
    symbol: 'TIA',
    price: 11.23,
    change24h: 5.67,
    change7d: 12.4,
    marketCap: 1_800_000_000,
    volume24h: 320_000_000,
    sparkline: generateSparkline(11, 0.04, 30, 0.1),
    alerts: 1,
  },
  {
    id: 'w6',
    name: 'Bittensor',
    symbol: 'TAO',
    price: 487.2,
    change24h: 7.89,
    change7d: 15.3,
    marketCap: 3_400_000_000,
    volume24h: 290_000_000,
    sparkline: generateSparkline(480, 0.05, 30, 0.15),
    alerts: 2,
  },
  {
    id: 'w7',
    name: 'Ondo',
    symbol: 'ONDO',
    price: 1.56,
    change24h: -1.34,
    change7d: 4.5,
    marketCap: 1_100_000_000,
    volume24h: 95_000_000,
    sparkline: generateSparkline(1.56, 0.03, 30, 0.04),
    alerts: 0,
  },
];

export const mockConvictions: ConvictionItem[] = [
  {
    id: 'c1',
    name: 'EigenLayer',
    symbol: 'EIGEN',
    thesis: 'Restaking will become the dominant security model for Ethereum ecosystem. EigenLayer is the category leader with insurmountable TVL lead.',
    convictionScore: 92,
    entryZone: '$2.80 - $3.20',
    target: '$8.50',
    stopLoss: '$2.10',
    positionSize: '5% portfolio',
    timeframe: '6-12 months',
    status: 'open',
    pnl: 18.4,
    category: 'Infrastructure',
  },
  {
    id: 'c2',
    name: 'Bittensor',
    symbol: 'TAO',
    thesis: 'AI + crypto convergence is the strongest narrative of the cycle. Bittensor is the only truly decentralized AI network with real usage.',
    convictionScore: 88,
    entryZone: '$380 - $420',
    target: '$1200',
    stopLoss: '$300',
    positionSize: '4% portfolio',
    timeframe: '12-18 months',
    status: 'open',
    pnl: 34.2,
    category: 'AI',
  },
  {
    id: 'c3',
    name: 'Pendle',
    symbol: 'PENDLE',
    thesis: 'Yield trading is a structural innovation. Pendle benefits from restaking yield and LRT ecosystem growth.',
    convictionScore: 85,
    entryZone: '$4.20 - $4.60',
    target: '$12.00',
    stopLoss: '$3.50',
    positionSize: '3% portfolio',
    timeframe: '6-9 months',
    status: 'open',
    pnl: 22.1,
    category: 'DeFi',
  },
  {
    id: 'c4',
    name: 'Celestia',
    symbol: 'TIA',
    thesis: 'Modular thesis is real. Celestia is the leading DA layer and will benefit as more rollups launch.',
    convictionScore: 78,
    entryZone: '$8.50 - $10.00',
    target: '$25.00',
    stopLoss: '$6.50',
    positionSize: '2.5% portfolio',
    timeframe: '9-12 months',
    status: 'open',
    pnl: 15.7,
    category: 'Infrastructure',
  },
  {
    id: 'c5',
    name: 'Solana',
    symbol: 'SOL',
    thesis: 'Solana has established itself as the leading alt-L1. Strong ecosystem growth, DePIN, and retail adoption.',
    convictionScore: 82,
    entryZone: '$120 - $145',
    target: '$300',
    stopLoss: '$95',
    positionSize: '4% portfolio',
    timeframe: '6-12 months',
    status: 'open',
    pnl: 42.3,
    category: 'L1',
  },
  {
    id: 'c6',
    name: 'Avalanche',
    symbol: 'AVAX',
    thesis: 'Gaming and subnet thesis. Positioned well for institutional adoption but momentum has cooled.',
    convictionScore: 62,
    entryZone: '$28 - $32',
    target: '$55',
    stopLoss: '$24',
    positionSize: '1.5% portfolio',
    timeframe: '6 months',
    status: 'closed',
    pnl: -8.3,
    category: 'L1',
  },
];

export const mockJournalEntries: JournalEntry[] = [
  {
    id: 'j1',
    title: 'Restaking TVL analysis: EigenLayer dominance and AVS economics',
    date: '2026-09-25',
    type: 'analysis',
    tags: ['Restaking', 'EigenLayer', 'DeFi'],
    excerpt: 'Deep dive into EigenLayer AVS economics. Analyzing TVL flows, slashing conditions, and operator incentives across 15 active AVS networks.',
    author: 'Research Team',
  },
  {
    id: 'j2',
    title: 'BTC cycle top indicators: What the data says about $90K+',
    date: '2026-09-24',
    type: 'thesis',
    tags: ['Bitcoin', 'Market Cycle', 'Macro'],
    excerpt: 'Reviewing on-chain metrics, MVRV, RHODL ratio, and NUPL. Current readings suggest mid-cycle, not local top.',
    author: 'Research Team',
  },
  {
    id: 'j3',
    title: 'Trade log: Added to TAO position on pullback',
    date: '2026-09-23',
    type: 'trade-log',
    tags: ['Bittensor', 'AI', 'Trade'],
    excerpt: 'Added 1% to TAO at $412. Conviction thesis unchanged. AI narrative momentum accelerating.',
    author: 'Portfolio Manager',
  },
  {
    id: 'j4',
    title: 'Observation: Solana DEX volume surpassing Ethereum for 3rd week',
    date: '2026-09-22',
    type: 'observation',
    tags: ['Solana', 'DEX', 'Volume'],
    excerpt: 'Solana DEX volume has consistently exceeded Ethereum for three consecutive weeks. Indicates retail activity migration.',
    author: 'Research Team',
  },
  {
    id: 'j5',
    title: 'RWA tokenization: Blackrock BUIDL fund crosses $500M',
    date: '2026-09-20',
    type: 'analysis',
    tags: ['RWA', 'Blackrock', 'Institutional'],
    excerpt: 'Blackrock BUIDL fund milestone. Institutional RWA adoption accelerating. Ondo and MakerDAO benefiting from spillover.',
    author: 'Research Team',
  },
  {
    id: 'j6',
    title: 'Thesis update: Modular blockchain ecosystem map',
    date: '2026-09-18',
    type: 'thesis',
    tags: ['Modular', 'Celestia', 'Infrastructure'],
    excerpt: 'Updated modular ecosystem map. 12 DA layers now live or in testnet. Celestia maintains lead but EigenDA gaining.',
    author: 'Research Team',
  },
];

export const mockNews: NewsItem[] = [
  {
    id: 'news1',
    headline: 'EigenLayer announces 3 new AVS networks going live next week',
    source: 'The Block',
    time: '2 hours ago',
    category: 'DeFi',
    sentiment: 'positive',
    impact: 'high',
    url: '#',
  },
  {
    id: 'news2',
    headline: 'Blackrock BUIDL fund surpasses $500M in AUM',
    source: 'CoinDesk',
    time: '4 hours ago',
    category: 'RWA',
    sentiment: 'positive',
    impact: 'high',
    url: '#',
  },
  {
    id: 'news3',
    headline: 'SEC delays decision on spot Solana ETF application',
    source: 'Bloomberg',
    time: '6 hours ago',
    category: 'Regulation',
    sentiment: 'neutral',
    impact: 'medium',
    url: '#',
  },
  {
    id: 'news4',
    headline: 'Bittensor subnet 23 reaches 1M+ model downloads',
    source: 'Messari',
    time: '8 hours ago',
    category: 'AI',
    sentiment: 'positive',
    impact: 'medium',
    url: '#',
  },
  {
    id: 'news5',
    headline: 'Ethereum gas fees hit 12-month low as L2 adoption grows',
    source: 'Glassnode',
    time: '12 hours ago',
    category: 'Ethereum',
    sentiment: 'positive',
    impact: 'low',
    url: '#',
  },
  {
    id: 'news6',
    headline: 'FTX estate announces final distribution plan for creditors',
    source: 'Reuters',
    time: '1 day ago',
    category: 'Industry',
    sentiment: 'positive',
    impact: 'medium',
    url: '#',
  },
  {
    id: 'news7',
    headline: 'Solana network experiences 4-hour partial outage',
    source: 'CoinDesk',
    time: '1 day ago',
    category: 'Solana',
    sentiment: 'negative',
    impact: 'medium',
    url: '#',
  },
  {
    id: 'news8',
    headline: 'Coinbase Q3 revenue beats estimates, institutional volume surges',
    source: 'Bloomberg',
    time: '2 days ago',
    category: 'Industry',
    sentiment: 'positive',
    impact: 'low',
    url: '#',
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 'e1',
    title: 'EigenLayer AVS #16 Mainnet Launch',
    date: '2026-09-28',
    time: '14:00 UTC',
    type: 'mainnet',
    project: 'EigenLayer',
    importance: 'high',
  },
  {
    id: 'e2',
    title: 'Solana ETF Decision Deadline',
    date: '2026-10-02',
    time: 'All day',
    type: 'governance',
    project: 'Solana',
    importance: 'high',
  },
  {
    id: 'e3',
    title: 'Celestia Token Unlock — 12M TIA',
    date: '2026-10-05',
    time: '00:00 UTC',
    type: 'token-unlock',
    project: 'Celestia',
    importance: 'medium',
  },
  {
    id: 'e4',
    title: 'Monad Public Testnet Phase 2',
    date: '2026-10-10',
    time: '16:00 UTC',
    type: 'mainnet',
    project: 'Monad',
    importance: 'medium',
  },
  {
    id: 'e5',
    title: 'Pendle V3 Announcement',
    date: '2026-10-12',
    time: '12:00 UTC',
    type: 'upgrade',
    project: 'Pendle',
    importance: 'high',
  },
  {
    id: 'e6',
    title: 'Bittensor Subnet 30 Launch',
    date: '2026-10-15',
    time: '18:00 UTC',
    type: 'mainnet',
    project: 'Bittensor',
    importance: 'medium',
  },
  {
    id: 'e7',
    title: 'Hyperliquid Token Listing',
    date: '2026-10-18',
    time: '14:00 UTC',
    type: 'listing',
    project: 'Hyperliquid',
    importance: 'high',
  },
  {
    id: 'e8',
    title: 'Coinbase Q3 Earnings Call',
    date: '2026-10-22',
    time: '21:00 UTC',
    type: 'earnings',
    project: 'Coinbase',
    importance: 'low',
  },
];

export const mockMarketCycle: MarketCyclePhase = {
  phase: 'Mid-Bull',
  description: 'BTC has cleared previous ATH and is in price discovery. On-chain metrics suggest mid-cycle positioning with room for further upside. Altcoin season index rising.',
  position: 55,
  startDate: '2024-01-15',
  indicators: [
    { label: 'MVRV Z-Score', value: '2.34', status: 'bullish' },
    { label: 'NUPL', value: '0.52', status: 'bullish' },
    { label: 'RHODL Ratio', value: '1,840', status: 'neutral' },
    { label: 'Reserve Risk', value: '0.0028', status: 'bullish' },
    { label: 'Puell Multiple', value: '1.42', status: 'neutral' },
    { label: 'Altcoin Season Index', value: '68', status: 'bullish' },
  ],
};

export const mockMacroIndicators: MacroIndicator[] = [
  {
    id: 'm1',
    label: 'DXY (Dollar Index)',
    value: '102.34',
    change: -0.42,
    trend: 'down',
    description: 'Dollar weakness supports risk assets. Declining trend since Fed pivot.',
    category: 'Currency',
    sparkline: generateSparkline(102, 0.005, 30, -0.02),
  },
  {
    id: 'm2',
    label: 'US 10Y Treasury Yield',
    value: '4.12%',
    change: -0.08,
    trend: 'down',
    description: 'Yields declining as market prices in rate cuts. Positive for crypto.',
    category: 'Rates',
    sparkline: generateSparkline(4.1, 0.01, 30, -0.03),
  },
  {
    id: 'm3',
    label: 'S&P 500',
    value: '5,847.2',
    change: 0.78,
    trend: 'up',
    description: 'Equities near all-time highs. Risk-on environment persists.',
    category: 'Equities',
    sparkline: generateSparkline(5800, 0.008, 30, 0.02),
  },
  {
    id: 'm4',
    label: 'Gold',
    value: '$2,648',
    change: 0.34,
    trend: 'up',
    description: 'Gold at record highs. Inflation hedge demand and central bank buying.',
    category: 'Commodities',
    sparkline: generateSparkline(2650, 0.01, 30, 0.03),
  },
  {
    id: 'm5',
    label: 'Fed Funds Rate',
    value: '4.75%',
    change: -0.25,
    trend: 'down',
    description: 'Fed began cutting cycle. 25bps cut at last FOMC meeting.',
    category: 'Rates',
    sparkline: generateSparkline(5, 0.003, 30, -0.05),
  },
  {
    id: 'm6',
    label: 'Global M2 Money Supply',
    value: '$94.2T',
    change: 0.52,
    trend: 'up',
    description: 'Global liquidity expanding. Historically bullish for crypto 6-12 weeks ahead.',
    category: 'Liquidity',
    sparkline: generateSparkline(94, 0.004, 30, 0.01),
  },
];

export const mockAIResearchSessions: AIResearchSession[] = [
  {
    id: 'a1',
    query: 'Analyze restaking ecosystem: TVL trends, AVS economics, and competitive landscape',
    status: 'completed',
    summary: 'EigenLayer maintains 78% market share in restaking. 15 active AVS networks with $2.1B delegated security. Key risk: slashing conditions and operator centralization.',
    sources: 24,
    date: '2026-09-25',
  },
  {
    id: 'a2',
    query: 'Compare modular DA layers: Celestia vs EigenDA vs Avail vs Near DA',
    status: 'completed',
    summary: 'Celestia leads in active rollups and light nodes. EigenDA leads in throughput. Avail has strongest data sampling. Near DA is cheapest but less decentralized.',
    sources: 18,
    date: '2026-09-24',
  },
  {
    id: 'a3',
    query: 'AI + crypto landscape: Which projects have real revenue vs pure narrative?',
    status: 'completed',
    summary: 'Bittensor has real subnet revenue. Fetch.ai and Ocean have limited on-chain revenue. Most AI tokens are narrative-driven with weak fundamentals.',
    sources: 31,
    date: '2026-09-22',
  },
  {
    id: 'a4',
    query: 'RWA tokenization institutional adoption: Blackrock, Franklin, Ondo analysis',
    status: 'in-progress',
    summary: 'Analyzing...',
    sources: 12,
    date: '2026-09-26',
  },
];

export const navItems: { label: string; href: string; icon: string; badge?: string }[] = [
  { label: 'Dashboard', href: '/', icon: 'LayoutDashboard' },
  { label: 'Market Cycle', href: '/market-cycle', icon: 'Repeat' },
  { label: 'Macro', href: '/macro', icon: 'Globe' },
  { label: 'Narrative Intelligence', href: '/narratives', icon: 'Brain' },
  { label: 'Project Research', href: '/research', icon: 'FileSearch' },
  { label: 'Watchlists', href: '/watchlists', icon: 'Eye' },
  { label: 'Convictions', href: '/convictions', icon: 'Target' },
  { label: 'Research Journal', href: '/journal', icon: 'BookOpen' },
  { label: 'News', href: '/news', icon: 'Newspaper' },
  { label: 'Calendar', href: '/calendar', icon: 'CalendarDays' },
  { label: 'AI Research', href: '/ai-research', icon: 'Sparkles', badge: 'BETA' },
  { label: 'Settings', href: '/settings', icon: 'Settings' },
];
